### ISSUE TITLE
例子征集

### ISSUE THREAD

**Issue by 892768447** [PyQt5/PyQt#1]
:joy:需要什么样的例子的请新增加Issues！:joy:

点击下面的链接

https://github.com/892768447/PyQt/issues/new

**Comment by heroxianf** [comment]
大神，我需要一个下拉菜单联动的示例，谢谢。

**Comment by dongzhang0725** [comment]
修改QFileSystemModel默认的ICON为自己自定义的ICON，或者把特定的ICON变成灰色。
![qq 20180126110230](https://user-images.githubusercontent.com/15956921/35423371-625700e0-0288-11e8-819b-bd3c8dd1c2f5.png)

**Comment by xtvjxk123456** [comment]
我想要一个气泡提示的，就是qq 聊天记录那种，会在桌面右下角进行提示，竖排的气泡，旧内容的气泡随着新的内容自动上浮并一段时间后消失，下面一直上浮新的消息
像这样子
![image](https://user-images.githubusercontent.com/8720281/35423543-2b0e635c-0289-11e8-9c34-64936e6aaa09.png)

**Comment by 892768447** [comment]
这样不好回复，请新增加Issues！ @heroxianf @dongzhang0725 @xtvjxk123456

**Comment by dongzhang0725** [comment]
修改QFileSystemModel默认的ICON为自己自定义的ICON，或者把特定的ICON变成灰色。

![qq 20180126110230](https://user-images.githubusercontent.com/15956921/35425520-4ee41774-0296-11e8-9278-fe31b7137f7e.png)
