### ISSUE TITLE
[问题] 关于demo中调用截图dll

### ISSUE THREAD

**Issue by SunRelease** [PyQt5/PyQt#104]
**Environment :** / 环境
 - OS: [e.g. Win 10]
 - Python [e.g. 3.6.4 X64]
 - PyQt5 [e.g. 5.10.1]

- 调用截图dll显示不是有效的win32程序,是不是要在32位系统下才能调用?,求大佬解答

**Comment by 892768447** [comment]
这个dll原本是qq里提取出来的。只支持32位
