### ISSUE TITLE
[问题] from Lib.flowlayout import FlowLayout 

### ISSUE THREAD

**Issue by xcxAscar** [PyQt5/PyQt#106]
- OS: Win 10
 - Python 3.5.1
 - PyQt5 5.13.2

引入报错
from Lib.flowlayout import FlowLayout

试过pip install Lib，但是import的时候没有Lib，能找到小写的（lib）

**Comment by 892768447** [comment]
Lib是项目例子的一个文件夹，在这里 https://github.com/PyQt5/PyQt/tree/master/QFlowLayout/Lib

**Comment by xcxAscar** [comment]
多谢解答
