### ISSUE TITLE
[问题] 用framelesswindow遇到的问题

### ISSUE THREAD

**Issue by tommyzoo** [PyQt5/PyQt#111]
**Environment :** / 环境
 - OS: [e.g. Win 10]
 - Python [e.g. 3.7.6 X64]
 - PyQt5 [e.g. 5.14.2]

大神你好，我套用了你的FramelessWindow代码,但是我在测试的时候发现，当快速移动几次窗口之后，有时按窗口中间也能拖动大小，有兴趣可以试一试。

**Comment by 625781186** [comment]
代码只提供学习 .
用于生产环境需要自己调整细节.

**Comment by 892768447** [comment]
@tommyzoo 
因为实现的方法多种多样，可能部分因素没考虑到。试试这个代码呢？
https://github.com/PyQt5/CustomWidgets/blob/master/TestCFramelessWidget.py
