### ISSUE TITLE
[问题]你好，我想问一下，我想在Qlabel里显示图片，画框并保存，该怎么做，查了很多，找不到相关案例，简单一点说，就是在label里实现截图保存功能，可以教我嘛

### ISSUE THREAD

**Issue by ggyybb** [PyQt5/PyQt#113]
**Environment :** / 环境
 - OS: [e.g. Win 10]
 - Python [e.g. 3.6.4 X64]
 - PyQt5 [e.g. 5.10.1]

( 读后删除以下段)
**Describe the bug** or **Expected behavior** ,
**Additional context** and **Screenshots**

// 描述你的问题 , 描述程序正常运行你希望的结果 , 提供程序的错误信息 和 源代码 截图 .
// 一次性把问题描述清楚 , 帮助者没时间一来一回地协助你描述清楚问题后再帮助你解决 ; 
// 2个来回后帮助者还不清楚你描述的问题 , 则会关闭提问.
// 如果代码过长 , 请创建一个仓库并附上链接.
---
如果需要贴代码 , 从下面2中格式 选一种

格式2 :
```python
(代码段)
```

( 读后删除以上段)

**Comment by 892768447** [comment]
1、重写 paintEvent 实现画图，参考 QPainter资料
2、保存界面截图用 grab()函数  https://doc.qt.io/qt-5/qwidget.html#grab
得到QPixmap对象。直接save保存
