### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.QAxContainer'

### ISSUE THREAD

**Issue by caiyingchun** [PyQt5/PyQt#115]
**Environment :** / 环境
 - OS: Win 10
 - Python 3.7.4 
 - PyQt5

I want use QAxWidget in my code, but when run code ```from PyQt5.QAxContainer import QAxWidget```, error raised:
```ModuleNotFoundError: No module named 'PyQt5.QAxContainer'```

Why?
Thanks

**Comment by 892768447** [comment]
1. Which PyQt5 version do you use?
2. use pip install PyQt5 -U
3. check Python/Lib/site-packages/PyQt5/QAxContainer.pyd

this is my test:
>>> from PyQt5.QAxContainer import QAxWidget
>>> QAxWidget
<class 'PyQt5.QAxContainer.QAxWidget'>
>>>

**Comment by caiyingchun** [comment]
@892768447 Thanks very much. 
I update pyqt5 using ```pip install PyQt5 -U```. It works.

**Comment by Gros19** [comment]
> @892768447 Thanks very much. I update pyqt5 using `pip install PyQt5 -U`. It works.
Thank you!
