### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Yodo92** [PyQt5/PyQt#116]
I was given this code to explore and find some places to refactor. Please, help me find some.

**Comment by Yodo92** [comment]
import json
from functools import partial

from PySide2 import QtCore, QtWidgets, QtGui
from DesktopApp.config import styles, widgets_names_ru

class IndicatorsSeason(QtWidgets.QGroupBox):
    """
    установка групбокса с показателями сезона
    indicators - список с показателями
    title - название групбокса
    """
    def __init__(self, parent, indicators: list, tooltips: list, title: str,
                 style: str = None):
        super(IndicatorsSeason, self).__init__(parent)

        self.values = []
        labels = []
        self.setTitle(title)

        for ind in indicators[:8]:
            label = QtWidgets.QLabel(self)
            label.setGeometry(QtCore.QRect(
                10, indicators[:8].index(ind) * 25 + 25, 50, 26))
            label.setText(ind)
            value = QtWidgets.QLabel(self)
            value.setGeometry(QtCore.QRect(
                70, indicators[:8].index(ind) * 25 + 26, 50, 25))
            value.setText("-")
            labels.append(label)
            self.values.append(value)

        for ind in indicators[8:]:
            label = QtWidgets.QLabel(self)
            label.setGeometry(QtCore.QRect(
                130, indicators[8:].index(ind) * 20 + 20, 50, 25))
            label.setText(ind)
            value = QtWidgets.QLabel(self)
            value.setGeometry(QtCore.QRect(
                190, indicators[8:].index(ind) * 20 + 20, 50, 25))
            value.setText("-")
            labels.append(label)
            self.values.append(value)

        labels = tuple(labels)
        for index in range(len(labels)):
            labels[index].setToolTip(tooltips[index])

        self.values = tuple(self.values)

    def set_values(self, values: list):
        """
        установка значений в групбокс команд по сезону
        :param values: список значений
        :return:
        """
        for label, value in zip(self.values, values):
            label.setText(str(value))


class IndicatorsMatch(QtWidgets.QWidget):
    """
    виджет с показателями матча
    """
    def __init__(self, parent):
        super(IndicatorsMatch, self).__init__(parent)

        self.names = widgets_names_ru

        self.h1_font = QtGui.QFont()
        self.h1_font.setPixelSize(styles["h1_size"])
        self.h1_font.setBold(True)

        self.h2_font = QtGui.QFont()
        self.h2_font.setPixelSize(styles["h2_size"])
        self.h2_font.setBold(True)

        self.big_font = QtGui.QFont()
        self.big_font.setPixelSize(styles["big_size"])
        self.big_font.setBold(True)

        self.p_font = QtGui.QFont()
        self.p_font.setPixelSize(styles["p_size"])
        self.p_font.setBold(True)

        self.color1 = styles['color_1_table']
        self.color2 = styles['color_2_table']

        self.home_indicators = []  # список для всех лейблов первой команды
        self.away_indicators = []

        self.first_box = QtWidgets.QGroupBox(self)
        self.first_box.setGeometry(0, 0, 680, 400)

        self.second_box = QtWidgets.QGroupBox(self)
        self.second_box.setGeometry(690, 0, 680, 400)

        self.third_box = QtWidgets.QGroupBox(self)
        self.third_box.setGeometry(0, 400, 680, 400)

        self.fourth_box = QtWidgets.QGroupBox(self)
        self.fourth_box.setGeometry(690, 400, 680, 400)

        self.home_name = QtWidgets.QLabel(self.first_box)
        self.home_name.setGeometry(10, 20, 290, 35)
        self.home_name.setText(
            self.names["box_widget_match"]["home_team"])

        self.result = QtWidgets.QLabel(self.first_box)
        self.result.setGeometry(310, 20, 60, 35)
        self.result.setText("0-0")
        self.result.setFont(self.h1_font)
        self.result.setAlignment(QtCore.Qt.AlignCenter)

        self.away_name = QtWidgets.QLabel(self.first_box)
        self.away_name.setGeometry(380, 20, 290, 35)
        self.away_name.setText(
            self.names["box_widget_match"]["away_team"])

        self.__set_first_labels()
        self.__set_second_labels()
        self.__set_third_labels()
        self.__set_fourth_labels()
        self.__set_styles()

    def set_values(self, values_home: list, values_away: list):
        """
        значения в списках:
        распишу как разберемся с моделью, значения изменятся
        :param values_home: значения показателей для домашней команды
        :param values_away: значения показателей для гостевой команды
        """
        values_home = list(values_home)
        values_away = list(values_away)
        for home_label, home_value, away_label, away_value in zip(
                self.home_indicators, values_home,
                self.away_indicators, values_away):
            if values_home.index(home_value) == 0:
                home_label.setText(f"{str(home_value)}%")
                away_label.setText(f"{str(away_value)}%")
            else:
                home_label.setText(str(home_value))
                away_label.setText(str(away_value))

    def __set_first_labels(self):
        """
        начальные настройки элементов первого групбокса
        """
        bp_title = QtWidgets.QLabel(self.first_box)
        bp_title.setGeometry(10, 70, 660, 25)
        bp_title.setText(self.names["box_widget_match"]["bp"])
        bp_title.setFont(self.h2_font)
        bp_title.setAlignment(QtCore.Qt.AlignCenter)

        home_bp = QtWidgets.QLabel(self.first_box)
        home_bp.setGeometry(10, 120, 290, 40)
        home_bp.setText("-")
        home_bp.setFont(self.big_font)
        home_bp.setAlignment(QtCore.Qt.AlignCenter)

        self.home_indicators.append(home_bp)

        away_bp = QtWidgets.QLabel(self.first_box)
        away_bp.setGeometry(380, 120, 290, 40)
        away_bp.setText("-")
        away_bp.setFont(self.big_font)
        away_bp.setAlignment(QtCore.Qt.AlignCenter)

        self.away_indicators.append(away_bp)

        hits_title = QtWidgets.QLabel(self.first_box)
        hits_title.setGeometry(10, 180, 660, 25)
        hits_title.setText(
            self.names["box_widget_match"]["hits"])
        hits_title.setFont(self.h2_font)
        hits_title.setAlignment(QtCore.Qt.AlignCenter)

        hits_labels = self.names["box_widget_match"]["first"]

        for index in range(len(hits_labels)):
            label = QtWidgets.QLabel(self.first_box)
            label.setGeometry(70, 230 + 22 * index, 540, 20)
            label.setText(hits_labels[index])
            label.setFont(self.p_font)
            label.setAlignment(QtCore.Qt.AlignCenter)

            home_ind = QtWidgets.QLabel(self.first_box)
            home_ind.setGeometry(10, 230 + 22 * index, 50, 20)
            home_ind.setText("-")
            home_ind.setFont(self.p_font)
            home_ind.setAlignment(QtCore.Qt.AlignCenter)

            away_ind = QtWidgets.QLabel(self.first_box)
            away_ind.setGeometry(620, 230 + 22 * index, 50, 20)
            away_ind.setText("-")
            away_ind.setFont(self.p_font)
            away_ind.setAlignment(QtCore.Qt.AlignCenter)

            self.home_indicators.append(home_ind)
            self.away_indicators.append(away_ind)

    def __set_second_labels(self):
        """
        начальные настройки элементов второго групбокса
        """
        passes_title = QtWidgets.QLabel(self.second_box)
        passes_title.setGeometry(10, 20, 660, 25)
        passes_title.setText(
            self.names["box_widget_match"]["passes"])
        passes_title.setFont(self.h2_font)
        passes_title.setAlignment(QtCore.Qt.AlignCenter)

        pass_labels = self.names["box_widget_match"]["second1"]

        for index in range(len(pass_labels)):
            label = QtWidgets.QLabel(self.second_box)
            label.setGeometry(70, 70 + index * 30, 540, 20)
            label.setText(pass_labels[index])
            label.setFont(self.p_font)
            label.setAlignment(QtCore.Qt.AlignCenter)

            home_ind = QtWidgets.QLabel(self.second_box)
            home_ind.setGeometry(10, 70 + 30 * index, 50, 20)
            home_ind.setText("-")
            home_ind.setFont(self.p_font)
            home_ind.setAlignment(QtCore.Qt.AlignCenter)

            away_ind = QtWidgets.QLabel(self.second_box)
            away_ind.setGeometry(620, 70 + 30 * index, 50, 20)
            away_ind.setText("-")
            away_ind.setFont(self.p_font)
            away_ind.setAlignment(QtCore.Qt.AlignCenter)

            self.home_indicators.append(home_ind)
            self.away_indicators.append(away_ind)


        duel_title = QtWidgets.QLabel(self.second_box)
        duel_title.setGeometry(10, 200, 660, 25)
        duel_title.setText(
            self.names["box_widget_match"]["duels"])
        duel_title.setFont(self.h2_font)
        duel_title.setAlignment(QtCore.Qt.AlignCenter)

        duel_labels = self.names["box_widget_match"]["second2"]

        for index in range(len(duel_labels)):
            label = QtWidgets.QLabel(self.second_box)
            label.setGeometry(70, 250 + index * 30, 540, 20)
            label.setText(duel_labels[index])
            label.setFont(self.p_font)
            label.setAlignment(QtCore.Qt.AlignCenter)

            home_ind = QtWidgets.QLabel(self.second_box)
            home_ind.setGeometry(10, 250 + 30 * index, 50, 20)
            home_ind.setText("-")
            home_ind.setFont(self.p_font)
            home_ind.setAlignment(QtCore.Qt.AlignCenter)

            away_ind = QtWidgets.QLabel(self.second_box)
            away_ind.setGeometry(620, 250 + 30 * index, 50, 20)
            away_ind.setText("-")
            away_ind.setFont(self.p_font)
            away_ind.setAlignment(QtCore.Qt.AlignCenter)

            self.home_indicators.append(home_ind)
            self.away_indicators.append(away_ind)

    def __set_third_labels(self):
        """
        начальные настройки элементов третьего групбокса
        """
        stat_name = QtWidgets.QLabel(self.third_box)
        stat_name.setGeometry(10, 20, 660, 25)
        stat_name.setText(
            self.names["box_widget_match"]["stat"])
        stat_name.setFont(self.h2_font)
        stat_name.setAlignment(QtCore.Qt.AlignCenter)

        statistics = self.names["box_widget_match"]["third"]

        for index in range(len(statistics)):
            label = QtWidgets.QLabel(self.third_box)
            label.setGeometry(70, 70 + index * 25, 540, 20)
            label.setText(statistics[index])
            label.setFont(self.p_font)
            label.setAlignment(QtCore.Qt.AlignCenter)

            home_ind = QtWidgets.QLabel(self.third_box)
            home_ind.setGeometry(10, 70 + 25 * index, 50, 20)
            home_ind.setText("-")
            home_ind.setFont(self.p_font)
            home_ind.setAlignment(QtCore.Qt.AlignCenter)

            away_ind = QtWidgets.QLabel(self.third_box)
            away_ind.setGeometry(620, 70 + 25 * index, 50, 20)
            away_ind.setText("-")
            away_ind.setFont(self.p_font)
            away_ind.setAlignment(QtCore.Qt.AlignCenter)

            self.home_indicators.append(home_ind)
            self.away_indicators.append(away_ind)

    def __set_fourth_labels(self):
        xg_name = QtWidgets.QLabel(self.fourth_box)
        xg_name.setGeometry(10, 20, 660, 25)
        xg_name.setText(
            self.names["box_widget_match"]["xg"])
        xg_name.setFont(self.h2_font)
        xg_name.setAlignment(QtCore.Qt.AlignCenter)
        xgs = self.names["box_widget_match"]["fourth"]

        for index in range(len(xgs)):
            label = QtWidgets.QLabel(self.fourth_box)
            label.setGeometry(70, 70 + index * 30, 540, 20)
            label.setText(xgs[index])
            label.setFont(self.p_font)
            label.setAlignment(QtCore.Qt.AlignCenter)

            home_ind = QtWidgets.QLabel(self.fourth_box)
            home_ind.setGeometry(10, 70 + 30 * index, 50, 20)
            home_ind.setText("-")
            home_ind.setFont(self.p_font)
            home_ind.setAlignment(QtCore.Qt.AlignCenter)

            away_ind = QtWidgets.QLabel(self.fourth_box)
            away_ind.setGeometry(620, 70 + 30 * index, 50, 20)
            away_ind.setText("-")
            away_ind.setFont(self.p_font)
            away_ind.setAlignment(QtCore.Qt.AlignCenter)

            self.home_indicators.append(home_ind)
            self.away_indicators.append(away_ind)

    def __set_styles(self):
        """
        настройка стилей для лейблов
        """
        self.home_name.setStyleSheet(f"color: rgb{self.color1}")
        self.home_name.setFont(self.h1_font)
        self.home_name.setAlignment(QtCore.Qt.AlignCenter)

        self.away_name.setStyleSheet(f"color: rgb{self.color2}")
        self.away_name.setFont(self.h1_font)
        self.away_name.setAlignment(QtCore.Qt.AlignCenter)

        for home, away in zip(self.home_indicators, self.away_indicators):
            home.setStyleSheet(f"color: rgb{self.color1}")
            away.setStyleSheet(f"color: rgb{self.color2}")


class OddsBox(QtWidgets.QGroupBox):
    """
    групбокс с коэффициентами букмекеров
    """
    def __init__(self, parent):
        super(OddsBox, self).__init__(parent)
        self.names = widgets_names_ru

        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(5, 80, 290, 310)

        self.lay = QtWidgets.QVBoxLayout()
        self.lay.setGeometry(QtCore.QRect(0, 0, 300, 300))

        self.widget.setLayout(self.lay)

        self.button = QtWidgets.QPushButton(self)
        self.button.setGeometry(10, 40, 280, 30)
        self.button.setText(self.names["odds"]["button"])

        self.font = QtGui.QFont()
        self.font.setPixelSize(styles["p_size"])
        self.font.setBold(True)

    def set_values(self, values: list):
        """
        установка кнопок с названиями букмекеров и их показателей
        :param values: список со словарями
        """
        values = sorted(values, key=lambda value: value["bookmaker"])
        for i in range(self.lay.count()):
            self.lay.itemAt(i).widget().setParent(None)

        self.menu = QtWidgets.QMenu(self.button)
        self.menu.setStyleSheet("menu-scrollable: 1")
        self.button.setMenu(self.menu)

        self.stack = QtWidgets.QStackedWidget()
        self.stack.setGeometry(0, 0, 300, 200)
        self.lay.addWidget(self.stack)

        labels_names = self.names["odds"]["labels"]
        buttons = []
        for value in values:
            scroll = QtWidgets.QScrollArea()
            self.stack.addWidget(scroll)
            widget = QtWidgets.QWidget()
            widget.setGeometry(0, 0, 240, 150)

            scroll.setWidget(widget)

            action = QtWidgets.QWidgetAction(self.button)

            button = QtWidgets.QPushButton()
            button.setText(str(value.pop("bookmaker")))
            v = values.index(value)
            button.clicked.connect(partial(self.stack.setCurrentIndex, v))

            action.setDefaultWidget(button)
            self.menu.addAction(action)
            buttons.append(button)

            index = 0
            for name in labels_names:
                val = value.get(name)
                if val is not None:
                    label = QtWidgets.QLabel(widget)
                    label.setGeometry(10, 10 + 25 * index, 90, 25)
                    label.setText(str(name))
                    label.setAlignment(QtCore.Qt.AlignLeft)
                    label.setFont(self.font)

                    label_val = QtWidgets.QLabel(widget)
                    label_val.setGeometry(110, 10 + 25 * index, 120, 25)
                    label_val.setText(str(val))
                    label_val.setAlignment(QtCore.Qt.AlignRight)
                    label_val.setFont(self.font)

                    widget.setFixedHeight(50 + 25 * index)
                    index += 1


class PredictsBox(QtWidgets.QGroupBox):
    """
    групбокс с прогнозами
    """
    def __init__(self, parent):
        super(PredictsBox, self).__init__(parent)

        self.names = widgets_names_ru

        self.font = QtGui.QFont()
        self.font.setPixelSize(styles["p_size"])
        self.font.setBold(True)
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(5, 30, 290, 360)

        self.lay = QtWidgets.QVBoxLayout()
        self.widget.setLayout(self.lay)

    def set_values(self, values: dict):
        """
        установка значений
        :param values: значения
        """
        for i in range(self.lay.count()):
            self.lay.itemAt(i).widget().setParent(None)

        scroll = QtWidgets.QScrollArea()
        self.stack = QtWidgets.QStackedWidget()  # без него почему то не работает
        self.stack.setGeometry(0, 0, 300, 200)
        self.lay.addWidget(self.stack)

        widget = QtWidgets.QWidget()
        widget.setMinimumWidth(240)
        scroll.setWidget(widget)

        self.stack.addWidget(scroll)

        labels_names = self.names["predicts"]["labels"]
        values.pop("match")
        values.pop("league_name")
        index = 0
        for name in labels_names:
            value = values.get(name)
            if value is not None:
                label = QtWidgets.QLabel(widget)
                label.setGeometry(10, 10 + 25 * index, 120, 25)
                label.setText(str(name))
                label.setAlignment(QtCore.Qt.AlignLeft)
                label.setFont(self.font)

                label_val = QtWidgets.QLabel(widget)
                label_val.setGeometry(130, 10 + 25 * index, 90, 25)
                label_val.setText(str(value))
                label_val.setAlignment(QtCore.Qt.AlignRight)
                label_val.setFont(self.font)

                widget.setFixedHeight(50 + 25 * index)
                index += 1

**Comment by 625781186** [comment]
@Yodo92 please provide `DesktopApp` .

**Comment by Yodo92** [comment]
Well, I dont have it for now. I need to refactor this code if possible.

**Comment by 625781186** [comment]
> Well, I dont have it for now. I need to refactor this code if possible.

As much as possible, provide a full working demo to upload to Github,

**Comment by 892768447** [comment]
> Well, I dont have it for now. I need to refactor this code if possible.

you want refactor this code to original as far as possible?

**Comment by Yodo92** [comment]
Well, I mean to rewrite in a more concise and clear way. As long as I'm completely new to PyQt, I can't see code pieces which can be rewritten in a more short form. Like: 
      ```
  self.h1_font = QtGui.QFont()
        self.h1_font.setPixelSize(styles["h1_size"])
        self.h1_font.setBold(True)

        self.h2_font = QtGui.QFont()
        self.h2_font.setPixelSize(styles["h2_size"])
        self.h2_font.setBold(True)
```
 To put in like `def bold_font(style="h1_size"):`

**Comment by 892768447** [comment]
you can use Qt designer to design your ui first
