### ISSUE TITLE
frozen certain column or row 

### ISSUE THREAD

**Issue by caiyingchun** [PyQt5/PyQt#117]
**Environment :** 
 - OS: Win 10
 - Python 3.7.7 X64
 - PyQt5 5.10.1

In ```QTableWidget```, How to frozen certain column or row, not allowing certain column or row moving along with scrollbar. I find an example in https://doc.qt.io/qt-5/qtwidgets-itemviews-frozencolumn-example.html, but it is a C++ example. Is there any such examples like this or how to achieve such effect in python?
Thanks a lot.

**Comment by 892768447** [comment]
you can see pyqt5 example here:  https://github.com/PyQt5/Examples/tree/master/PyQt5/itemviews/frozencolumn

**Comment by caiyingchun** [comment]
Thanks a lot
