### ISSUE TITLE
Crash only in pyqt window

### ISSUE THREAD

**Issue by NicoliHCorrea** [PyQt5/PyQt#118]
I'm writing a code to read from a OED (like a CSV) file and plot the data. 
When I run the code by itself, it works just fine. But when I try to incorporate it to a pyqt window, it crashes. 
PS: When I read a CSV file, it works. The problem is with the OED file. 
I'll add a few prints and the code. 

Other file plotted in the  pyqt window
![image](https://user-images.githubusercontent.com/58525689/93006569-27058880-f534-11ea-94a8-3301f4a46d29.png)
Only the plot in a separated area
![image](https://user-images.githubusercontent.com/58525689/93006595-7ea3f400-f534-11ea-8472-eed4589779f3.png)

Code:
1- The update of the plotting area

```
def update_samples_file_oed(self, labels):
        nome_arq = self.openFileNameDialog()
        if nome_arq:
            dados_filtrados = end_funcs.read_arq(r'{}'.format(nome_arq) , self.plot_type)
            self.fig.suptitle(os.path.basename(nome_arq))
            self.path = nome_arq
            if self.reset_samples(True):
                self.plot(dados_filtrados, plot_type_axis_x=self.type_axis_x)
                self.update_table(labels, dados_filtrados)
            else:
                pass
        else:
            pass
```

OBS: If I comment the self.plot line, the code works. 

2- The plotting
 ```
def plot(self, data, plot_type_axis_x='Samples'):
        self.type_axis_x = plot_type_axis_x
        self.data = data
        self.create_axes()
        self.create_plot(self.data, self.type_axis_x)
        self.draw()
```
3- The creation of the plot
   ```
 def create_plot(self, data, plot_type_axis_x):
        if (self.plot_line):
            self.show_vector()

        self.set_grids()
        self.set_labels_and_titles(plot_type_axis_x)

        self.ax1.plot(data[:, 1], data[:, 2])

        # Plot com numero da aquisição no eixo X
        if plot_type_axis_x == 'Samples':
            self.ax2.plot(data[:, 1], label='Resistance')
            self.ax3.plot(data[:, 2], label='Inductive reactance')

        # Plot com tempo no eixo X
        elif plot_type_axis_x == 'Time':
            self.ax2.plot(data[:, 0], data[:, 1], label='Resistance')
            self.ax3.plot(data[:, 0], data[:, 2], label='Inductive reactance')
```

Please, if anyone has any idea of what it could be, comment here and help me. Thank you!

**Comment by 892768447** [comment]
try add at the beginning of the code
```
import cgitb
cgitb.enable(format="text")
```

and run in shell or cmd

Maybe you can see an some exception

**Comment by NicoliHCorrea** [comment]
> 
> 
> try add at the beginning of the code
> 
> ```
> import cgitb
> cgitb.enable(format="text")
> ```
> 
> and run in shell or cmd
> 
> Maybe you can see an some exception

I got "MemoryError: Unable to allocate 2.86 GiB for an array with shape (19586, 19586) and data type float64"

I don't see why this is happening.. So I tried to plot only part of the data, like the first 2000 points, and it worked. When I tried 6000 points it took a while, but still worked. But with 10000 it crashed again.

If the problem is the size of the array, why when I run the function alone there's no crashing or error?

**Comment by 892768447** [comment]
are you sure use python 64bit not 32bit

**Comment by NicoliHCorrea** [comment]
I'm using 64bits version.. and I have 333GB free in my HD and 14,2GB free on my SSD

**Comment by 892768447** [comment]
I guess the current system is running have not enough free memory
you can test like:

before:
![image](https://user-images.githubusercontent.com/5131669/93008501-f0695580-f5a7-11ea-9a3e-b205abe833fb.png)

after:
![image](https://user-images.githubusercontent.com/5131669/93008505-02e38f00-f5a8-11ea-8a3e-93be0cbd19fa.png)

again:
![image](https://user-images.githubusercontent.com/5131669/93008513-14c53200-f5a8-11ea-979d-38d60e72b243.png)

![image](https://user-images.githubusercontent.com/5131669/93008521-39210e80-f5a8-11ea-8831-5a97f2eb70ba.png)

**Comment by NicoliHCorrea** [comment]
So I tested on my computer and I got like 98% of my RAM like you. But I have 16GB. 
I tested the code that is working separately and it didn't use even 50% of my RAM. 
Do you have any idea why reading from the same file and plotting the same graph is causing this difference in performance? The only difference is that one is running through a Pyqt window and the other isn't.

**Comment by 892768447** [comment]
maybe read file code? every time a large file is read, memory will increase, how big is the test file？
you can run code and watch computer RAM. 
According to the abnormal information and picture information. It's really an exception thrown by the numpy module.

$ pip install -U memory_profiler
$ pip install psutil

use `memory_profiler` or some other memory module test your code and analyzing memory problems

**Comment by NicoliHCorrea** [comment]
The file is 384KB.

**Comment by 625781186** [comment]
If your code `isn't complex` and `doesn't need privacy`, 
it's best to put your entire project to us to test.

Of course, too much complexity is unnecessary.

**Comment by NicoliHCorrea** [comment]
I tried to make the other files that are working the same size as this one (20K samples) and the graph took a while to show but still worked. So I think that the size is what is affecting the performance, I just don't know why this only happens on the pyqt window. 
Right now it's late here (00h) so I can't talk to my partner about this, but tomorrow I'll come back with more information or doubts.

The code is really big and it's private, I'll try to make a smaller version that keeps the problem so that I can send it here. 
Anyway, you already helped me A LOT. Thank you very much!

**Comment by NicoliHCorrea** [comment]
So, I found out that the problem was in another function that was being called in the pyqt window. This function made the plot crash, even though there was nothing to do with that. 
Thank you for trying to help me.
Is someone is going through the same, I recommend trying to delete everything on the pyqt window like buttons, group boxes, etc, and keep testing it. If the problem is only when you run the pyqt window, the problem must be there.
