### ISSUE TITLE
[问题] Remove the dotted box around the button

### ISSUE THREAD

**Issue by Mohammadwh** [PyQt5/PyQt#119]
![image](https://user-images.githubusercontent.com/18552903/93067630-b45def80-f690-11ea-983e-a49d22083f89.png)

hello how i can remove droped box around my button ? :(

**Comment by 892768447** [comment]
What stylesheet did you use?

border: 1px solid red;

**Comment by Mohammadwh** [comment]
QPushButton{border: 1px solid black; border-color: rgb(219, 79, 208); color: white;font: bold 14px; background-color: rgba(219, 79, 208,10);}

**Comment by Mohammadwh** [comment]
here you are❤

**Comment by 892768447** [comment]
use tab key to switch buttons may be casue like this

**Comment by Mohammadwh** [comment]
pyqt5 droped this automatic

**Comment by 892768447** [comment]
you can add this
outline: 0;
