### ISSUE TITLE
How to sort data in QTableWidget?

### ISSUE THREAD

**Issue by caiyingchun** [PyQt5/PyQt#121]
Environment :

OS: Win 10
Python 3.7.7 X64
PyQt5 5.10.1

I have a QTableWidget and the first column contains numbers from 1 to 1000. Now I need to sort the table based on this first column.
I'm using the function ```sortItems(int column, Qt::AscendingOrder)```, but it is displayed as:
**1, 10, 100, 1000, 101, 102, ...**
Yet I need this result:
**1, 2, 3 ,4...., 1000.**

How to do it? Thanks a lot.

**Comment by 892768447** [comment]
It's usually sorted by strings, not numbers. so `sortItems` will not work ok.
you can use `QTableView` and [QSortFilterProxyModel](https://doc.qt.io/qt-5/qsortfilterproxymodel.html#lessThan) to do that

**Comment by 892768447** [comment]
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Created on 2020/10/10
@author: Irony
@site: https://pyqt.site , https://github.com/892768447
@email: 892768447@qq.com
@file: 
@description: 
"""
from PyQt5.QtWidgets import QApplication, QTableWidget, QTableWidgetItem


class QTableNumberItem(QTableWidgetItem):

    def __lt__(self, other):
        try:
            return int(self.text()) < int(other.text())
        except:
            return super(QTableNumberItem, self).__lt__(other)


if __name__ == '__main__':
    import sys

    app = QApplication(sys.argv)
    w = QTableWidget()
    w.setSortingEnabled(True)
    w.show()
    w.setColumnCount(2)
    w.setRowCount(30)
    for i in range(30):
        item = QTableNumberItem(str(i))
        w.setItem(i, 0, item)
    sys.exit(app.exec_())

```

**Comment by caiyingchun** [comment]
Thanks a lot. It works.
