### ISSUE TITLE
qwebchannel 如何导入到vue框架中

### ISSUE THREAD

**Issue by mr-tan4** [PyQt5/PyQt#123]
**Environment :** / 环境
 - OS: [mac os x 10.15.7 ]
 - Python [3.7.5 x64]
 - PyQt5 [5.15.1]
- PyQtWebEngine [5.15.1]
我准备在前端项目中点击按钮用来触发python中的方法
但是在前端中引入qwebchannel后点击按钮报错了
这是代码
```
    @pyqtSlot(str)
    def show_Plan(self, str):
        self.root_postion.default_hide_camera()
        self.root_postion.came_info[str].setDisabled(False)
        self.root_postion.came_info[str].show()

    @pyqtSlot()
    def hide_camera(self):
        self.root_postion.default_hide_camera()
```
![image](https://user-images.githubusercontent.com/15813848/99625466-4c9a9b00-2a6b-11eb-94a0-1996cdb259f4.png)
![image](https://user-images.githubusercontent.com/15813848/99625632-a00ce900-2a6b-11eb-8a90-f254db0fb618.png)
![image](https://user-images.githubusercontent.com/15813848/99625644-a307d980-2a6b-11eb-9de4-f207280ac1cd.png)
![image](https://user-images.githubusercontent.com/15813848/99625796-f37f3700-2a6b-11eb-85dc-c5d6e2eb94b2.png)

请问有什么好的解决方案吗？

**Comment by 892768447** [comment]
按理说不会。你是最后转为js么，import xxx.js 不确定能工作。
这里有交互例子
https://github.com/PyQt5/PyQt/blob/master/QWebEngineView/JsSignals.py

**Comment by WorkSync** [comment]
> **Environment :** / 环境
> 
> * OS: [mac os x 10.15.7 ]操作系统：[mac os x 10.15.7]
> * Python [3.7.5 x64]
> * PyQt5 [5.15.1]
> * PyQtWebEngine [5.15.1]
>   我准备在前端项目中点击按钮用来触发python中的方法
>   但是在前端中引入qwebchannel后点击按钮报错了
>   这是代码
> 
> ```
>     @pyqtSlot(str)
>     def show_Plan(self, str):
>         self.root_postion.default_hide_camera()
>         self.root_postion.came_info[str].setDisabled(False)
>         self.root_postion.came_info[str].show()
> 
>     @pyqtSlot()
>     def hide_camera(self):
>         self.root_postion.default_hide_camera()
> ```
> 
> ![image](https://user-images.githubusercontent.com/15813848/99625466-4c9a9b00-2a6b-11eb-94a0-1996cdb259f4.png) ![image](https://user-images.githubusercontent.com/15813848/99625632-a00ce900-2a6b-11eb-8a90-f254db0fb618.png) ![image](https://user-images.githubusercontent.com/15813848/99625644-a307d980-2a6b-11eb-9de4-f207280ac1cd.png) ![image](https://user-images.githubusercontent.com/15813848/99625796-f37f3700-2a6b-11eb-85dc-c5d6e2eb94b2.png)
> 
> 请问有什么好的解决方案吗？

我也想在pyqt5里面用vue/react，可以请教一下吗

**Comment by 892768447** [comment]
你可以试一下node环境里安装这个js。
或者配置下生成最终的html页面里单独引入这个js

**Comment by 892768447** [comment]
@mr-tan4 @WorkSync 

`npm i qwebchannel`


## index.html
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite App</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>

```

## main.js
```javascript
import { createApp } from 'vue'
import { QWebChannel } from 'qwebchannel'
import App from './App.vue'

new QWebChannel(qt.webChannelTransport,
    function(channel) {
        window.Bridge = channel.objects.Bridge;
    }
);

createApp(App).mount('#app')

```

## App.vue
```javascript
<script>
export default {
  // reactive state
  data() {
    return {
      count: 0
    }
  },

  // functions that mutate state and trigger updates
  methods: {
    increment() {
      this.count++
      Bridge.callFromJs(`The count is ${this.count}.`)
    }
  },

  // lifecycle hooks
  mounted() {
    console.log(`The initial count is ${this.count}.`)
  }
}
</script>

<template>
  <button @click="increment">Count is: {{ count }}</button>
</template>

```

最后使用 https://github.com/PyQt5/PyQt/blob/master/QWebEngineView/JsSignals.py 测试打开的url
