### ISSUE TITLE
[问题] 请问大神ScreenShot.dll有没64位版本

### ISSUE THREAD

**Issue by jsnjfz** [PyQt5/PyQt#124]
因为项目中还需要调用其他的64位dll文件，如果使用
CDLL('ScreenShot.dll')
就会报[WinError 193] %1 不是有效的 Win32 应用程序。
想请问下大神ScreenShot.dll有没64位版本

**Comment by 892768447** [comment]
这个是从QQ里提取出来的.只有32位.
不过你可以换个方法. 写一个32位的exe去调用这个dll.
然后你的64位的程序里可以去执行这个32位的exe.这样是没有问题的
