### ISSUE TITLE
[问题] 文件QWebEngineView.SiteDiffUser：reCaptcha 不能正常加载

### ISSUE THREAD

**Issue by ANXIETIER** [PyQt5/PyQt#125]
我在Window.__init__()中把加载网页那一行换成
```python
self.webView2.load(QUrl('https://www.google.com/recaptcha/api2/demo'))
```
这是加载reCaptcha的demo网页，当我注释掉下面
```python
        profile2 = QWebEngineProfile('storage2', self.webView2)
        profile2.setPersistentStoragePath('Tmp/Storage2')
        print(profile2.cookieStore())
        page2 = QWebEnginePage(profile2, self.webView2)
        self.webView2.setPage(page2)
```
以后，可以正常加载，但我想保留这部分，有解决方案吗

**Comment by 892768447** [comment]
你是想修改cookie的保存路径么。如果这样有问题。你可以不用修改。可以用过 persistentStoragePath 获取原来的cookie目录
https://doc.qt.io/qt-5/qwebengineprofile.html#persistentStoragePath

**Comment by 892768447** [comment]
![111](https://user-images.githubusercontent.com/5131669/216247578-db5e590f-8d8e-4699-80de-d19de9e0c75d.gif)

测试挂了代理后两个页面都显示了。但是点击有点卡，有时候加载很慢

**Comment by 892768447** [comment]
测试发现问题出现在路径上。
设置为相对路径下 `profile2.setPersistentStoragePath('Tmp/Storage2')` 需要改为绝对路径

这样就可以了
`profile2.setPersistentStoragePath(os.path.abspath('Tmp/Storage2'))`
