### ISSUE TITLE
[问题] 无法找到库

### ISSUE THREAD

**Issue by lyhlyhl** [PyQt5/PyQt#131]
**Environment :** / 环境
 - OS: [e.g. Win 10]
 - Python [e.g. 3.8.5 X64]
 - PyQt5 [e.g. 5.15.2]
 - pyqtgraph 0.11.1

该历程[https://github.com/PyQt5/PyQt/blob/master/PyQtGraph/graph1.py](https://github.com/PyQt5/PyQt/blob/master/PyQtGraph/graph1.py)

代码

```python
from PyQtGraph.Data.graphTest import graph_Form
```
无法运行，找不到库，已经安装了pyqtgraph，但是不太清楚作者的大写PyQtGraph有啥区别

**Comment by 892768447** [comment]
@lyhlyhl 
cmd中输入你的python进入后 import 试试。是不是按照成功了PyQtGraph，可能有时候是虚拟环境

最好的办法是 绝对路径/python -m pip install pyqtgraph
这样就会安装到指定的python中

**Comment by 892768447** [comment]
@lyhlyhl  emmm 这个和库安装没关系。主要是这个项目有自己的目录
https://github.com/PyQt5/PyQt/tree/master/PyQtGraph/Data
在这里
最好是把整个项目下载下来

**Comment by lyhlyhl** [comment]
嗯嗯，已经找到了，感谢大佬项目，学到了很多嘿嘿。
不过我是把整个项目下载下来的，在pycharm下面，路径可能不太对
原文是
`from PyQtGraph.Data.graphTest import graph_Form`
我发现Data文件夹是在PyQtGraph下面，所以更改成
`from Data.graphTest import graph_Form`
就可以运行了
