### ISSUE TITLE
[怎么把py文件转为ui文件？] 

### ISSUE THREAD

**Issue by dgl547437235** [PyQt5/PyQt#137]

**Comment by 892768447** [comment]
目前是没有直接的方法反向转换
不过你可以参考 PyQt 里 uic这个模块 反向解析py文件生成xml
或者参考 https://doc.qt.io/qt-5/qobject.html#dumpObjectTree 和 https://doc.qt.io/qt-5/qobject.html#dumpObjectInfo
根据层级结构反向构造ui文件
