### ISSUE TITLE
有人m1的mac安装成功过pyqt5么。

### ISSUE THREAD

**Issue by bbhxwl** [PyQt5/PyQt#138]
有人m1的mac安装成功过pyqt5么。

**Comment by 892768447** [comment]
基于ARM的需要自己编译

**Comment by bbhxwl** [comment]
> 基于ARM的需要自己编译

没编译过，是不是挺复杂的，不能像pip这样安装。

**Comment by 892768447** [comment]
https://www.riverbankcomputing.com/static/Docs/PyQt5/installation.html#building-and-installing-from-source

**Comment by bbhxwl** [comment]
> 基于ARM的需要自己编译

我倒是有树莓派能安装的pyqt5 的whl，好像在m1 上不行。

**Comment by 892768447** [comment]
1、测试了m1可以跑x64的Qt， 但是该Qt编译的PyQt也是x64，而系统里的python3是arm的。导致不能混合使用
2、办法就是先编译 arm的Qt， 然后再编译对应的PyQt

**Comment by 892768447** [comment]
@bbhxwl 

The simplest solution:
1. https://www.python.org/downloads/macos/
2. download Python 3.9.13 - May 17, 2022 [Download macOS 64-bit Intel-only installer  https://www.python.org/ftp/python/3.9.13/python-3.9.13-macosx10.9.pkg](https://www.python.org/ftp/python/3.9.13/python-3.9.13-macosx10.9.pkg)
3. install python-3.9.13-macosx10.9.pkg

   **进入自定义**

![屏幕截图 2023-10-07 105612](https://github.com/PyQt5/PyQt/assets/5131669/42cb7be5-3f9f-4b4f-a4f6-eeac6b19ee98)

   **只需要勾选 Install or upgrade pip**

![屏幕截图 2023-10-07 104323](https://github.com/PyQt5/PyQt/assets/5131669/ad40f47d-2e6e-40ab-88fd-4803cb4b3977)

5. /Library/Frameworks/Python.framework/Versions/3.9/bin/pip3 install PyQt5
6. /Library/Frameworks/Python.framework/Versions/3.9/bin/python3

![屏幕截图 2023-10-07 104707](https://github.com/PyQt5/PyQt/assets/5131669/c426d299-541f-4f0e-b88a-58a5bf785aa9)
