### ISSUE TITLE
aero snap support for "24、无边框窗口" demo

### ISSUE THREAD

**Issue by mustafaahci** [PyQt5/PyQt#139]
**Environment :** / 环境
 - OS: Win10
 - Python 3.9.5 X64
 - PyQt5 5.15.4 & PySide2 5.15.2

Hello ヽoo悾絔℅o。, I love your works and thank you so much for those examples.
I have an issue with your "24、无边框窗口" demo project. I saw aero snap support on your gif of the project.
But i can't see any aero support function when i run it on my computer. I tried pyqt5 and pyside2 as well.
Does it have aero support in the end or do you have any idea why it doesn't work for me?

Sorry, i don't speak Chinese.

**Comment by 892768447** [comment]
it's test on Deepin Linux System.
on windows, frameless window will lost aero snap effect default.
you can see and use some windows api to fix it
https://www.daimajiaoliu.com/daima/3855863b3900403/qtzihuibiaotihebiankuang
https://github.com/deimos1877/BorderlessWindow
