### ISSUE TITLE
NativeEvent - Maximize window issue

### ISSUE THREAD

**Issue by shironori66** [PyQt5/PyQt#142]
**Environment :** / 环境
 - OS: Win 10
 - Python 3.9 X64
 - PyQt5 e.g. 5.15.1

Hi. I am trying your [NativeEvent.py](https://github.com/PyQt5/PyQt/blob/master/Demo/NativeEvent.py) demo. I have trouble maximize the window. This sample worked perfectly but after I added WS_CAPTION in SetWindowLong() for a window animation, I encountered an issue. When i maximize the window, the part mentioned in [line ~80](https://github.com/PyQt5/PyQt/blob/master/Demo/NativeEvent.py#L80) does not work. But if i change that line to "self._rect.height() - 1", it works again but as you can see the window height is not fit to the screen. There is a 1px space and i don't know why the window has to be a bit smaller than the available space.

**Comment by upmanager** [comment]
Thanks for your sample. but I can't run that sample code.

>   File "D:\test.py", line 51, in nativeEvent
>     x = win32api.LOWORD(msg.lParam) - self.frameGeometry().x()
> OverflowError: Python int too large to convert to C long

show this error, What is that?

**Comment by 892768447** [comment]
https://github.com/zhiyiYo/PyQt-Frameless-Window
