### ISSUE TITLE
[问题] PyQt5-tools 安装完成后， Qt 设计师找不到任何插件

### ISSUE THREAD

**Issue by Deteriorator** [PyQt5/PyQt#148]
**Environment :** / 环境
 - OS: Win 10
 - Python 3.9.9 X64
 - PyQt5 5.15.4

先后安装了 PyQt5 和 PyQt5-tools

```bash
pip install PyQt5
pip install PyQt5-tools
```
 正常安装后， 打开 designer.exe, 点击帮助的 关于插件， 发现没有任何插件， 这个问题怎么解决？
![image](https://user-images.githubusercontent.com/31269745/150363784-4b969688-b1c9-4d97-8742-88a78b66eb8a.png)

**Comment by 892768447** [comment]
designer 本来就默认不带任何插件。pyqt5-tools是采用自己编译得
如果缺少webengineview 则需要从官方Qt designer目录中拷贝过来

**Comment by Deteriorator** [comment]
> designer 本来就默认不带任何插件。pyqt5-tools是采用自己编译得 如果缺少webengineview 则需要从官方Qt designer目录中拷贝过来

我是否可以修改 designer.exe 同级目录的 qt.conf 文件， 达到指定 plugin 目录的目的？

**Comment by 892768447** [comment]
应该可以。不过就几个文件。拷贝过去就行了。

**Comment by Deteriorator** [comment]
> designer 本来就默认不带任何插件。pyqt5-tools是采用自己编译得 如果缺少webengineview 则需要从官方Qt designer目录中拷贝过来

从官方拷贝， 是不是得安装 QT 啊？ QT 太大了

**Comment by 892768447** [comment]
https://github.com/PyQt5/QtDesigner
https://github.com/PyQt5/QtDesignerPlugins

删掉插件里面的 workspaceplugin5.dll

**Comment by 892768447** [comment]
不想用扩展插件也可以全部删掉
logplugin5.dll
menusplugin5.dll
pyqtplugin5.dll
qsseditorplugin5.dll
websocketplugin5.dll
workspaceplugin5.dll

**Comment by Deteriorator** [comment]
我用 pyqt5-tools 安装的是 5.15.4 版本的， github 上的好像是 5.15.0 版本， 可以兼容么？ 就害怕报无法导入

**Comment by 892768447** [comment]
这是独立程序，不是库

**Comment by Deteriorator** [comment]
好的， 我试试， 多谢
