### ISSUE TITLE
pip3 install pyqt5 fails on aarch64

### ISSUE THREAD

**Issue by bhlevca** [PyQt5/PyQt#150]
**Environment :
 - OS: [debian aarch64]
 - Python [ 3.7.3]
 - PyQt5 [e.g. 5.10.1]
 - 

**Describe the bug** or **Expected behavior** ,

command `pip3 install pyqt5`  fails

**Additional context** and **Screenshots**
```
pip3 install pyqt5
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyqt5
  Using cached https://files.pythonhosted.org/packages/3b/27/fd81188a35f37be9b3b4c2db1654d9439d1418823916fe702ac3658c9c41/PyQt5-5.15.6.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-7g0eq6ep/pyqt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7g0eq6ep/pyqt5/

```A clear and concise description of what the bug is.

**Comment by 892768447** [comment]
This project is just some PyQt examples

https://pypi.org/project/PyQt5/#files 
As you can see, There is no precompiled package for this platform.
You can add Debian's third-party source and install it through apt command

**Comment by 892768447** [comment]
Or you can install QT first and then compile the corresponding version of pyqt5 yourself

**Comment by bhlevca** [comment]
Thanks, it was useful. I installed with apt and then I removed pyqt5 from the list of required packages so that pip3 does not crash.

**Comment by ilg-ul** [comment]
> There is no precompiled package for this platform.

Would it be possible to add precompiled packages for aarch64?

**Comment by bhlevca** [comment]
The solution I proposed above for the aarch64 packages that have a pyqt5 dependency  with pip is a temporary hack.  

The real  solution is to add PyQt5-5.15.6-cp36-abi3-manylinux1_aarch64.whl at https://pypi.org/project/PyQt5/#files

**Comment by 892768447** [comment]
Because [riverbankcomputing](https://www.riverbankcomputing.com/software/pyqt/) didn't provide arm package.

solutions:
1. Configure official source or third-party source, and use apt or yum to install.
2. Install Qt first, then build PyQt5 from source

**Comment by bhlevca** [comment]
Thanks, but that's a hack and we already have a solution by installing with apt and no compilation from source is needed. The idea is to have an elegant solution for all pip packages with pyqt5  requirements.

I already filed a bug report with Riverbank Computing asking to provide an aarch64 whl file in the pypi repository.
