### ISSUE TITLE
widget.setMask multiple rects in pyQt5

### ISSUE THREAD

**Issue by upmanager** [PyQt5/PyQt#163]
https://stackoverflow.com/questions/72833464/widget-setmask-multiple-rects-in-pyqt5

**Comment by 892768447** [comment]
maybe you can use paintEvent

like:

```python
class PaintWidget(QWidget):

    def paintEvent(self, event):
        painter = QPainter(self)
        painter.setPen(QPen(1, Qt.black))
        painter.fillRect(self.rect(), Qt.yellow)
```

**Comment by upmanager** [comment]
I want make mask for yellow area.
So, Hope to show only yellow area on widget, and other side want to hide.
