### ISSUE TITLE
Windows minimize, maximize animation not working for FramelessWindow.

### ISSUE THREAD

**Issue by upmanager** [PyQt5/PyQt#164]
**Environment :**
 - OS: [e.g. Win 10]
 - Python [e.g. 3.9.1 X64]
 - PyQt5 [e.g. 5.15.4]

Here is the default animation for minimize and maximize.
![anim](https://user-images.githubusercontent.com/89163655/178039277-6f115d0d-b47b-4d92-be2e-03bb779f5774.gif)

and When i add FramelessWindowHint flag, Not working animation.
![no anim](https://user-images.githubusercontent.com/89163655/178039338-f2d123cf-e9cb-4c3c-8622-6122ca2f23f2.gif)

**Comment by 892768447** [comment]
https://github.com/PyQt5/PyQt/issues/142

**Comment by 892768447** [comment]
https://github.com/PyQt5/PyQt/issues/139
