### ISSUE TITLE
无边框窗口在Mac平台时无法最小化

### ISSUE THREAD

**Issue by hehonghui** [PyQt5/PyQt#165]
**Environment :** / 环境
 - OS: MacOs Big Sur 11.6
 - Python 3.8
 - PyQt5 5.15.6

问题如标题描述, 测试程序为: https://github.com/PyQt5/PyQt/blob/master/Demo/NewFramelessWindow.py

**Comment by 892768447** [comment]
已修复最小化问题，但是resize 无法调整大小，可以先参考下其它几个无边框例子

**Comment by hehonghui** [comment]
> 已修复最小化问题，但是resize 无法调整大小，可以先参考下其它几个无边框例子

感谢支持!  还有哪些无边框的方案推荐使用呢 ？

**Comment by hehonghui** [comment]
另外我测试了一下，https://github.com/PyQt5/PyQt/commit/566f75e54d8974c5e45ba958b9f9436bba62e4d8 这个提交没有解决问题，窗口最小化是可以，但是没法恢复回来。

**Comment by 892768447** [comment]
https://github.com/PyQt5/PyQt/blob/master/Demo/FramelessWindow.py

这是是用原始python模拟支持的。不利用系统api。当然最小化可能一样存在问题。
这个可以百度搜索到  Qt 无边框 最小化无效

**Comment by 892768447** [comment]
> 另外我测试了一下，[566f75e](https://github.com/PyQt5/PyQt/commit/566f75e54d8974c5e45ba958b9f9436bba62e4d8) 这个提交没有解决问题，窗口最小化是可以，但是没法恢复回来。https://gitee.com/feiyangqingyun/QWidgetDemo/tree/master/widget/framelesswidget 这个C++的示例中 QMainWindow 类型可以实现正常的最小化、恢复，其他类型的也是有些异常。

对。这个修复我尝试过。也有问题。
我提交的代码在 我的mac版本里可以恢复。任务栏点击。可以还原
