### ISSUE TITLE
PyQt有办法内嵌cocoa的红绿灯组件吗

### ISSUE THREAD

**Issue by ghost** [PyQt5/PyQt#181]

**Comment by 892768447** [comment]
macos cocoa 红绿灯组件？ 具体是哪个

**Comment by duhiqc** [comment]
> macos可可红绿灯组件？具体是哪个

![image](https://user-images.githubusercontent.com/114081461/219824072-8a58994d-3a02-4241-99ce-c53a38358144.png)

**Comment by 892768447** [comment]
这个是系统标题栏，mac的系统标题栏中间区域可以自定义内容

**Comment by 892768447** [comment]
https://www.freesion.com/article/8785338861/
