### ISSUE TITLE
How do I implement my own custom element for QGraphicsScene?

### ISSUE THREAD

**Issue by Aleksandr34nov** [PyQt5/PyQt#183]
**Environment :** / 环境
 - OS: [e.g. Win 10]
 - Python [e.g. 3.6.4 X64]
 - PyQt5 [e.g. 5.10.1]

Hello
I am implementing a program for rendering various objects. I use QGraphicsView together with QGraphicsScene for rendering.

I need to implement the rendering of my own custom element. One of these elements is the scale in the photo below:
![Scale](https://user-images.githubusercontent.com/80050858/219989014-345b16ad-9d02-4a9f-9e23-ef8849f65c93.png)

How can this be done? Maybe there are examples of the implementation of any custom elements? There is an idea to inherit QGraphicsRectItem for a custom element class, but I don't really understand which methods need to be redefined and which conditions need to be met. I would be very grateful for an example of some custom element. Or would it be better to inherit some other class?

**Comment by 892768447** [comment]
here some example: https://github.com/PyQt5/Examples/tree/master/PyQt5/graphicsview
