### ISSUE TITLE
窗口贴边隐藏demo在ubuntu系统中不行

### ISSUE THREAD

**Issue by LeeXujie** [PyQt5/PyQt#187]
WeltHideWindow.py程序在ubuntu系统中贴边不隐藏

**Comment by 892768447** [comment]
linux下 gnome 不支持Qt的无边框窗口 通过函数方式（move）移动到屏幕外。被窗口管理器限制导致

**Comment by 892768447** [comment]
可以通过隐藏窗口 和 创建1px的边框0.1 透明线条在屏幕边缘来检测鼠标实现
