### ISSUE TITLE
Adding music player examples

### ISSUE THREAD

**Issue by Wonderful99668** [PyQt5/PyQt#33]
If the repo could add a simple music player example, that would be great :)

**Comment by 892768447** [comment]
Sorry，No planning in the near future，but there are some good example:

https://github.com/clementine-player/Clementine
https://github.com/wang-bin/QtAV
https://github.com/HMKRL/PyQt-MusicPlayer
https://github.com/caiwb/MusicPlayer-PyQT
https://github.com/chxuan/CZPlayer
https://github.com/Greedysky/TTKMusicplayer  (支持网易云音乐、QQ音乐、虾米音乐、酷我音乐、酷狗音乐、百度音乐等等)
https://www.linux-apps.com/content/show.php?content=129372
https://www.tomahawk-player.org/
https://flavio.tordini.org/musique

**Comment by Wonderful99668** [comment]
Thx : )
