### ISSUE TITLE
QtWebEngeinChannel

### ISSUE THREAD

**Issue by Singein** [PyQt5/PyQt#35]
不知阁下是否有兴趣研究论证一番我们使用 一些特殊的手段 设计出使用 Python + PyQt WebEngein打造的对HTML+CSS+JS前端技术兼容的框架呢， 简单的说，我们能不能用现有的Python框架，完成Electron一样的事儿呢...

**Comment by 892768447** [comment]
emmm，这个，在几年前毕设得时候我就用的qwebkit做过了。后来webengine出来的时候，和js交互有bug，加上后来Electron比较完善了。所以对这方面不是很感兴趣

**Comment by 892768447** [comment]
emmm，这个，在几年前毕设得时候我就用的qwebkit做过了。后来webengine出来的时候，和js交互有bug，加上后来Electron比较完善了。所以对这方面不是很感兴趣

**Comment by Singein** [comment]
用qwebchannel能实现 python对js对象的访问吗

**Comment by 892768447** [comment]
可以的，之前是很不方便，现在好像好多了。可以直接调用py里定义的槽函数。过段时间写例子。

**Comment by Singein** [comment]
OK👌。 顺便安利一下我之前用pyqt写的一个项目 https://github.com/Singein/Healthy-Work
