### ISSUE TITLE
嵌入Word、excel等后问题

### ISSUE THREAD

**Issue by jishubu** [PyQt5/PyQt#37]
1、嵌入后，能否居中显示Word、Excel内容；
2、嵌入后，能否设置不允许编辑状态；
3、嵌入后，能否设置编辑状态下，显示Word、excel的工具栏；
4、嵌入后，能否完成编辑并进行保存；
5、嵌入后，能否正常进行退出；

**Comment by 892768447** [comment]
目前的QAxWidget不能实现复杂功能
