### ISSUE TITLE
新增下面动图的效果

### ISSUE THREAD

**Issue by dongzhang0725** [PyQt5/PyQt#38]
![jdfw](https://user-images.githubusercontent.com/15956921/54538903-16706280-49d0-11e9-85e5-080b7f666553.gif)

请老大有时间做一个这个动图里面的效果的例子。

**Comment by bkdwei** [comment]
> 
> 
> ![jdfw](https://user-images.githubusercontent.com/15956921/54538903-16706280-49d0-11e9-85e5-080b7f666553.gif)
> 
> 请老大有时间做一个这个动图里面的效果的例子。

1. 按钮的浮动，可以使用QDockWidget,将QDockWidget.addWidget(QPushBotton)。
2. 按钮的浮动，也可以通过重新mousePressEvent和mouseMoveEvent事件实现。可自行百度“无边框窗口的移动".
3. 点击按钮弹出菜单。点击按钮后，以定点为起点，以某一角度为间隔，计算其他按钮在圆上的位置，并放置按钮即可。

**Comment by dongzhang0725** [comment]
好的，多谢
