### ISSUE TITLE
在QtableWidge中如何通过点击按钮得到所在的行数

### ISSUE THREAD

**Issue by zhusimaji51** [PyQt5/PyQt#41]
def  confirm(self):
        mask_btn=self.sender()
        model=self.model()
        btn_index = self.indexAt(mask_btn.parent().mapFromGlobal(QCursor.pos()))
        row=btn_index.row()

**Comment by 625781186** [comment]
![image](https://user-images.githubusercontent.com/30521429/56948716-93603180-6b63-11e9-9ff1-b6bb5adfda69.png)

思路 通过 鼠标坐标 转换成 程序内的坐标 , 获得索引 ,获取行号

![image](https://user-images.githubusercontent.com/30521429/56948645-5b58ee80-6b63-11e9-9a84-e1af8fa64c2c.png)
