### ISSUE TITLE
qprocess 64为系统。32为程序调用系统程序问题

### ISSUE THREAD

**Issue by 625781186** [PyQt5/PyQt#44]
![image](https://user-images.githubusercontent.com/30521429/58161891-afaf4400-7cb3-11e9-94b6-448dc8e2afc0.png)
![image](https://user-images.githubusercontent.com/30521429/58161902-b9d14280-7cb3-11e9-95ba-ae85367e9491.png)

**Comment by 625781186** [comment]
![image](https://user-images.githubusercontent.com/30521429/58162034-f69d3980-7cb3-11e9-9e86-41d995deac97.png)

注 :
`os.system`, `os.startfile ` 之类都不行

**Comment by 892768447** [comment]
![QQ图片20190522190151](https://user-images.githubusercontent.com/5131669/58169759-1f2d2f80-7cc4-11e9-914b-d9a0e199236d.png)

**Comment by 892768447** [comment]
```python
import ctypes
import os

redv = 0
try:
    oldValue = ctypes.c_long(0)
    redv = ctypes.windll.kernel32.Wow64DisableWow64FsRedirection(ctypes.byref(oldValue))
    print(oldValue, redv)
except:
    pass

os.startfile(r'C:\Windows\System32\osk.exe')

if redv:
    try:
        ctypes.windll.kernel32.Wow64RevertWow64FsRedirection(oldValue)
    except:
        pass

```
