### ISSUE TITLE
判断GridLayout是否为空

### ISSUE THREAD

**Issue by Yaojifeng** [PyQt5/PyQt#45]

**Comment by 625781186** [comment]
>1.QT版本: http://doc.qt.io/qt-5/qgridlayout.html;
2.pyside2版本: https://doc-snapshots.qt.io/qtforpython/search.html?q=qgridlayout
![image](https://user-images.githubusercontent.com/30521429/58255730-33def580-7da0-11e9-891f-0623827885f8.png)
![image](https://user-images.githubusercontent.com/30521429/58255739-3a6d6d00-7da0-11e9-8e81-b655347e973c.png)
可以看到 , 文档说明 count()函数返回items的数量
