### ISSUE TITLE
使用JsonDocument的时候会报错

### ISSUE THREAD

**Issue by tvvbbb** [PyQt5/PyQt#47]
```python
QJsonDocument({"abc": QJsonValue("abc")})
```
如果运行以上代码程序会闪退，只能使用以下代码（去掉QJsonValue）：
```python
QJsonDocument({"abc": "abc"})
```
上面的用法有什么错误呢？

**Comment by 892768447** [comment]
首先文档说明，支持4中类型的参数：
```c++
QJsonDocument(QJsonDocument &&other)
QJsonDocument(const QJsonDocument &other)
QJsonDocument(const QJsonArray &array)
QJsonDocument(const QJsonObject &object)
```

解释下

`QJsonArray`  <=> Python中的 `list`
`QJsonObject`  <=> Python中的 `dict`

而这种用法`QJsonDocument({"abc": "abc"})`可能是因为PyQt或者PySide在绑定库的时候做了处理，至于第一种写法估计识别不了导致的

**Comment by tvvbbb** [comment]
在pyqt的文档上如下：
```python
__init__(Dict[str, Union[QJsonValue, Type, Iterable[QJsonValue], bool, int, float, str]])
```
这个就是在一个dict里面，key是str，value是union里面其中一种就可以了。

**Comment by 892768447** [comment]
```
QJsonDocument()
QJsonDocument(Dict[str, QJsonValue])
QJsonDocument(Iterable[Union[QJsonValue, QJsonValue.Type, Dict[str, QJsonValue], bool, int, float, str]])
QJsonDocument(QJsonDocument)
```
嗯。提示确实是这样，我测试`QJsonDocument({"a": QJsonValue("abc")})`这样也会报错，但是如果你用python的dict语法，又嵌套Qt的对象在里面总感觉很怪异，不建议混合用。

**Comment by tvvbbb** [comment]
你的pyqt文档是去哪里找的？最古怪的是官方给出了这样的文档，但又会报错，才是最头疼的，而且pyqt里面也没有全套qt的操作，形象实不是吧

**Comment by 892768447** [comment]
LiClipse编辑器里的提示，有时候有的构造参数是有问题，尽量不混合用

**Comment by tvvbbb** [comment]
官方真的有点坑
