### ISSUE TITLE
关于多进程，信号问题。

### ISSUE THREAD

**Issue by BuildDreams** [PyQt5/PyQt#48]
在主界面里面，开启多个进程，将信号传递给子进程，依此来更新主界面对应的进度条，发现子进程不能发送信号给主界面。老哥来个例子

**Comment by 625781186** [comment]
> 在主界面里面，开启多个进程，将信号传递给子进程，依此来更新主界面对应的进度条，发现子进程不能发送信号给主界面。老哥来个例子

信号槽只用于线程 , 进程的话 百度 python进程通信.

**Comment by 625781186** [comment]
@BuildDreams

QT Remote Objects 能用于进程通信 , 但是pyqt还未支持 .

[http://python.6.x6.nabble.com/QT-Remote-Objects-td5245285.html](http://python.6.x6.nabble.com/QT-Remote-Objects-td5245285.html)

**Comment by 892768447** [comment]
@BuildDreams  使用QLocalSocket 通信也不错

**Comment by 625781186** [comment]
@BuildDreams 
那个模块出了 
https://github.com/PyQt5/PyQt/tree/master/QtRemoteObjects#1modelview

**Comment by 892768447** [comment]
@BuildDreams  不要慌。我会写个简单的中文例子

**Comment by 892768447** [comment]
https://github.com/PyQt5/PyQt/tree/master/QtRemoteObjects#3%E7%AE%80%E5%8D%95%E7%95%8C%E9%9D%A2%E6%95%B0%E6%8D%AE%E5%90%8C%E6%AD%A5
