### ISSUE TITLE
可视化界面对接需求的问题

### ISSUE THREAD

**Issue by HXChow** [PyQt5/PyQt#49]
做了个可视化界面来实现需求代码中的功能
![image](https://user-images.githubusercontent.com/51086267/60568041-42a4c900-9d9e-11e9-9911-4f9e9c6537c7.png)
![image](https://user-images.githubusercontent.com/51086267/60568183-b2b34f00-9d9e-11e9-8c67-9207af4ce6ce.png)

想通过图中的“确定”按钮来实现  “选择图片文件夹 -- 选择排序方式 -- 排序”的功能
具体信号与槽函数如下
![image](https://user-images.githubusercontent.com/51086267/60568142-8dbedc00-9d9e-11e9-9eaf-27abf8cf869b.png)
![image](https://user-images.githubusercontent.com/51086267/60568156-98797100-9d9e-11e9-8746-61cb1d3f8cf3.png)

这是需求代码
![image](https://user-images.githubusercontent.com/51086267/60568222-d24a7780-9d9e-11e9-82af-c715c5e534be.png)
![image](https://user-images.githubusercontent.com/51086267/60568229-d7a7c200-9d9e-11e9-911d-f2c31fdd90e4.png)

目前出现的问题为无法实现需求
望群主不吝赐教

**Comment by 625781186** [comment]
> 做了个可视化界面来实现需求代码中的功能
> ![image](https://user-images.githubusercontent.com/51086267/60568041-42a4c900-9d9e-11e9-9911-4f9e9c6537c7.png)
> ![image](https://user-images.githubusercontent.com/51086267/60568183-b2b34f00-9d9e-11e9-8c67-9207af4ce6ce.png)
> 
> 想通过图中的“确定”按钮来实现 “选择图片文件夹 -- 选择排序方式 -- 排序”的功能
> 具体信号与槽函数如下
> ![image](https://user-images.githubusercontent.com/51086267/60568142-8dbedc00-9d9e-11e9-9eaf-27abf8cf869b.png)
> ![image](https://user-images.githubusercontent.com/51086267/60568156-98797100-9d9e-11e9-8746-61cb1d3f8cf3.png)
> 
> 这是需求代码
> ![image](https://user-images.githubusercontent.com/51086267/60568222-d24a7780-9d9e-11e9-82af-c715c5e534be.png)
> ![image](https://user-images.githubusercontent.com/51086267/60568229-d7a7c200-9d9e-11e9-911d-f2c31fdd90e4.png)
> 
> 目前出现的问题为无法实现需求
> 望群主不吝赐教

你提供的代码看不出问题

**Comment by 625781186** [comment]
@HXChow 
你提供的代码看不出问题 , 自己新建一个仓库 , 提交完整代码.

**Comment by 892768447** [comment]
你这不是排序了吧。是重命名文件了。而且会直接影响硬盘上的文件，不建议这样。可以直接在软件里显示图片。并做排序。可以用 QListView（或者QFileSystemModel） + QSortFilterProxyModel 实现不同的排序显示

**Comment by HXChow** [comment]
> 你这不是排序了吧。是重命名文件了。而且会直接影响硬盘上的文件，不建议这样。可以直接在软件里显示图片。并做排序。可以用 QListView（或者QFileSystemModel） + QSortFilterProxyModel 实现不同的排序显示

待会我把代码上传一下

**Comment by HXChow** [comment]
> 你这不是排序了吧。是重命名文件了。而且会直接影响硬盘上的文件，不建议这样。可以直接在软件里显示图片。并做排序。可以用 QListView（或者QFileSystemModel） + QSortFilterProxyModel 实现不同的排序显示

https://github.com/HXChow/PYQT5
代码已经上传了

**Comment by 625781186** [comment]
> > 你这不是排序了吧。是重命名文件了。而且会直接影响硬盘上的文件，不建议这样。可以直接在软件里显示图片。并做排序。可以用 QListView（或者QFileSystemModel） + QSortFilterProxyModel 实现不同的排序显示
> 
> https://github.com/HXChow/PYQT5
> 代码已经上传了
> 在Tab 2界面

现在的问题是什么? 信号槽无法连接? 还是功能错误?

**Comment by HXChow** [comment]
> 你这不是排序了吧。是重命名文件了。而且会直接影响硬盘上的文件，不建议这样。可以直接在软件里显示图片。并做排序。可以用 QListView（或者QFileSystemModel） + QSortFilterProxyModel 实现不同的排序显示
> 
> https://github.com/HXChow/PYQT5
> 代码已经上传了
> 在Tab 2界面
> 
> 现在的问题是什么? 信号槽无法连接? 还是功能错误?

功能单运行需求文件没问题可以实现
应该是信号槽的问题，但是我揪不出来，劳请您帮忙看一下，麻烦您了！
这是一个练手项目我负责可视化界面方面，需求代码不是我写的

**Comment by 625781186** [comment]
> > 你这不是排序了吧。是重命名文件了。而且会直接影响硬盘上的文件，不建议这样。可以直接在软件里显示图片。并做排序。可以用 QListView（或者QFileSystemModel） + QSortFilterProxyModel 实现不同的排序显示
> > https://github.com/HXChow/PYQT5
> > 代码已经上传了
> > 在Tab 2界面
> > 现在的问题是什么? 信号槽无法连接? 还是功能错误?
> 
> 功能单运行需求文件没问题可以实现
> 应该是信号槽的问题，但是我揪不出来，劳请您帮忙看一下，麻烦您了！
> 这是一个练手项目我负责可视化界面方面，需求代码不是我写的

https://space.bilibili.com/1863103/#/ 教程 第2讲 .

**Comment by HXChow** [comment]
> 你这不是排序了吧。是重命名文件了。而且会直接影响硬盘上的文件，不建议这样。可以直接在软件里显示图片。并做排序。可以用 QListView（或者QFileSystemModel） + QSortFilterProxyModel 实现不同的排序显示
> https://github.com/HXChow/PYQT5
> 代码已经上传了
> 在Tab 2界面
> 现在的问题是什么? 信号槽无法连接? 还是功能错误?
> 
> 功能单运行需求文件没问题可以实现
> 应该是信号槽的问题，但是我揪不出来，劳请您帮忙看一下，麻烦您了！
> 这是一个练手项目我负责可视化界面方面，需求代码不是我写的
> 
> https://space.bilibili.com/1863103/#/ 教程 第2讲 .

就是说我现在界面和逻辑并没有分离是吧

**Comment by HXChow** [comment]
> 你这不是排序了吧。是重命名文件了。而且会直接影响硬盘上的文件，不建议这样。可以直接在软件里显示图片。并做排序。可以用 QListView（或者QFileSystemModel） + QSortFilterProxyModel 实现不同的排序显示
> https://github.com/HXChow/PYQT5
> 代码已经上传了
> 在Tab 2界面
> 现在的问题是什么? 信号槽无法连接? 还是功能错误?
> 功能单运行需求文件没问题可以实现
> 应该是信号槽的问题，但是我揪不出来，劳请您帮忙看一下，麻烦您了！
> 这是一个练手项目我负责可视化界面方面，需求代码不是我写的
> https://space.bilibili.com/1863103/#/ 教程 第2讲 .
> 
> 就是说我现在界面和逻辑并没有分离是吧



> 你这不是排序了吧。是重命名文件了。而且会直接影响硬盘上的文件，不建议这样。可以直接在软件里显示图片。并做排序。可以用 QListView（或者QFileSystemModel） + QSortFilterProxyModel 实现不同的排序显示
> https://github.com/HXChow/PYQT5
> 代码已经上传了
> 在Tab 2界面
> 现在的问题是什么? 信号槽无法连接? 还是功能错误?
> 
> 功能单运行需求文件没问题可以实现
> 应该是信号槽的问题，但是我揪不出来，劳请您帮忙看一下，麻烦您了！
> 这是一个练手项目我负责可视化界面方面，需求代码不是我写的
> 
> https://space.bilibili.com/1863103/#/ 教程 第2讲 .

我界面和逻辑已经分开了然后

> 你这不是排序了吧。是重命名文件了。而且会直接影响硬盘上的文件，不建议这样。可以直接在软件里显示图片。并做排序。可以用 QListView（或者QFileSystemModel） + QSortFilterProxyModel 实现不同的排序显示
> https://github.com/HXChow/PYQT5
> 代码已经上传了
> 在Tab 2界面
> 现在的问题是什么? 信号槽无法连接? 还是功能错误?
> 功能单运行需求文件没问题可以实现
> 应该是信号槽的问题，但是我揪不出来，劳请您帮忙看一下，麻烦您了！
> 这是一个练手项目我负责可视化界面方面，需求代码不是我写的
> https://space.bilibili.com/1863103/#/ 教程 第2讲 .
> 
> 就是说我现在界面和逻辑并没有分离是吧

我现在界面和逻辑已经分离了

> 你这不是排序了吧。是重命名文件了。而且会直接影响硬盘上的文件，不建议这样。可以直接在软件里显示图片。并做排序。可以用 QListView（或者QFileSystemModel） + QSortFilterProxyModel 实现不同的排序显示
> https://github.com/HXChow/PYQT5
> 代码已经上传了
> 在Tab 2界面
> 现在的问题是什么? 信号槽无法连接? 还是功能错误?
> 
> 功能单运行需求文件没问题可以实现
> 应该是信号槽的问题，但是我揪不出来，劳请您帮忙看一下，麻烦您了！
> 这是一个练手项目我负责可视化界面方面，需求代码不是我写的
> 
> https://space.bilibili.com/1863103/#/ 教程 第2讲 .

我现在界面和逻辑已经分离了，但是还是与需求界面连接不成功，无法实现功能

**Comment by HXChow** [comment]
> 你这不是排序了吧。是重命名文件了。而且会直接影响硬盘上的文件，不建议这样。可以直接在软件里显示图片。并做排序。可以用 QListView（或者QFileSystemModel） + QSortFilterProxyModel 实现不同的排序显示
> https://github.com/HXChow/PYQT5
> 代码已经上传了
> 在Tab 2界面
> 现在的问题是什么? 信号槽无法连接? 还是功能错误?
> 功能单运行需求文件没问题可以实现
> 应该是信号槽的问题，但是我揪不出来，劳请您帮忙看一下，麻烦您了！
> 这是一个练手项目我负责可视化界面方面，需求代码不是我写的
> https://space.bilibili.com/1863103/#/ 教程 第2讲 .
> 
> 就是说我现在界面和逻辑并没有分离是吧

我现在界面和逻辑已经分离，但是还是无法与需求对接成功，无法实现功能（无法通过一个按钮来完成需求的内容）
https://github.com/HXChow/project

**Comment by 625781186** [comment]
@HXChow 
在按钮连接的函数里加print() 来打印看看是否触发了函数 ;

**Comment by HXChow** [comment]
> @HXChow
> 在按钮连接的函数里加print("xxxx") 来打印看看是否触发了函数 ;

能打印出来
在点击确定后反馈的错误是“Process finished with exit code -1073740791 (0xC0000409)”
窗口闪退

**Comment by 625781186** [comment]
> > @HXChow
> > 在按钮连接的函数里加print("xxxx") 来打印看看是否触发了函数 ;
> 
> 能打印出来
> 在点击确定后反馈的错误是“Process finished with exit code -1073740791 (0xC0000409)”
> 窗口闪退

如果是pycharm运行 , 请在群里机器人 查看如何让pycharm提示错误 ; 
或者在cmd中运行脚本 , 我看了你的代码 , 参数不对.

**Comment by HXChow** [comment]
> @HXChow
> 在按钮连接的函数里加print("xxxx") 来打印看看是否触发了函数 ;
> 
> 能打印出来
> 在点击确定后反馈的错误是“Process finished with exit code -1073740791 (0xC0000409)”
> 窗口闪退
> 
> 如果是pycharm运行 , 请在群里机器人 查看如何让pycharm提示错误 ;
> 或者在cmd中运行脚本 .
> 我看了你的代码 , 参数不对.

是哪些参数错误
