### ISSUE TITLE
导入模块报错提示蓝牙的API好像是

### ISSUE THREAD

**Issue by Johnny0710** [PyQt5/PyQt#57]
Python 代码
`from PyQt5.Qt import *`

错误提示

> This Windows version(6.3.9600)does not support the requiredBluetooth Apl. Consider updating to a more recent Windows(10.0.10586 or above)

**Comment by 892768447** [comment]
@Johnny0710 
错误提示里说的，你现在用的pyqt模块编译的版本中蓝牙模块不支持 系统版本10.0.10586以下的系统
