### ISSUE TITLE
[问题] 解决pyqt内置html页面动态加载后截取整个html页面的的图片

### ISSUE THREAD

**Issue by sunboy123** [PyQt5/PyQt#58]
同时截取的部分包括看到的和需要滚动才可以看到的页面

**Environment :** / 环境
 - OS: Win 10
 - Python [e.g. 3.6.4 X64]
 - PyQt5 [e.g. 5.10.1]

**Comment by 892768447** [comment]
见：https://github.com/PyQt5/PyQt/blob/master/QWebView/ScreenShotPage.py

**Comment by 892768447** [comment]
高版本见：https://github.com/PyQt5/PyQt/blob/master/QWebEngineView/ScreenShotPage.py
