### ISSUE TITLE
[问题]软换行有可能转换为硬换行吗？

### ISSUE THREAD

**Issue by teyying** [PyQt5/PyQt#59]
比如**QTextEdit**设置了软换行，能否实现把它的软换行变成硬换行？因为自己在插入时按像素或者字符长度调整时，无法达到预期效果。而软换行的效果是自己想要的，但前提是能实现通过什么方法把它转换成硬换行，不知道软换行的地方是否能得到什么标记？本人水平很菜，提的问题可能有点可笑，还望别在意。

**Comment by 625781186** [comment]
@teyying 什么是软换行和硬换行

**Comment by teyying** [comment]
> @teyying什么是软换行和硬换行

软换行其实本质是在一行的内容，只不过编辑器显示不完，自动往下换行。而硬换行相当于我们在需要换行的位置按下了**回车键**

**Comment by 625781186** [comment]
@teyying 
![image](https://user-images.githubusercontent.com/30521429/60791489-5ed9a900-a196-11e9-91a9-176d34ffaa2a.png)
![image](https://user-images.githubusercontent.com/30521429/60791602-95172880-a196-11e9-9c79-532caf4db8c7.png)
应该是这个吧

**Comment by teyying** [comment]
不是这个意思，因为我想要得到真正的行，而自己实现不了，应该说是自己实现的换行方式没有`setLineWrapMode`的方式效果好。而我不想设置`setLineWrapMode`，我想自己处理。算了，这个问题自己也感觉有点不太好。。。我应该自己再尝试着解决‘\n'前的逻辑处理。**非常感谢！**
