### ISSUE TITLE
[问题]Qlabel 播放视频

### ISSUE THREAD

**Issue by HXChow** [PyQt5/PyQt#61]
**Environment :** / 环境
 - OS: Win10
 - Python 3.7.2 x64
 - PyQt5 5.11.3

一个合成视频的功能
![image](https://user-images.githubusercontent.com/51086267/61166173-3d910800-a55c-11e9-950d-25e21e2bf953.png)
要在合成视频完后在视频预览的label内播放视频
想通过在视频合成完后发射信号的方法来自动预览视频
![image](https://user-images.githubusercontent.com/51086267/61166186-74ffb480-a55c-11e9-9751-e03d0812d12c.png)
![image](https://user-images.githubusercontent.com/51086267/61166202-c3ad4e80-a55c-11e9-819a-a76a1791fea3.png)
上图中的signal3是发射播放视频的信号，Update_3获取合成后的视频位置并播放

目前出现的问题是无法在label那播放视频，请问是不是方法用错了？

**Comment by 892768447** [comment]
@HXChow  QLabel不能播放视频，只能显示图片或者gif动态图。
而QMediaPlayer 可以播放视频，但是它没有解码库，需要以来系统里自己按照解码库，，在win10上默认可以播放wmv格式的视频
