### ISSUE TITLE
[问题]QtabWidget 是否与Qwidget相冲突？

### ISSUE THREAD

**Issue by HXChow** [PyQt5/PyQt#62]
**Environment :** / 环境
 OS: Win10
Python 3.7.2 x64
PyQt5 5.11.3]

弄了一个widget，将其提升为myVideoWidget来播放视频
但是在实际运行时这个控件出了问题
这是在QT designer预览的样子
![image](https://user-images.githubusercontent.com/51086267/61181737-c2634b00-a65c-11e9-91cf-7054b3cc8b28.png)
运行时切换上面红线的tab界面会导致这个控件将其他tab相对应的区域的界面截取下来
效果是这样的
![image](https://user-images.githubusercontent.com/51086267/61181764-022a3280-a65d-11e9-8e0c-2842db2f2c06.png)
把其他tab的区域截取了下来。就出了这个显示问题，其他功能一切正常
请问该如何解决这个问题，最近问题比较多轻喷，望不吝赐教

**Comment by HXChow** [comment]
抱歉忘记添加题目了

**Comment by 892768447** [comment]
QTabWidget没有这个问题啊，具体看下你代码里怎么切换tab的

**Comment by HXChow** [comment]
> QTabWidget没有这个问题啊，具体看下你代码里怎么切换tab的

https://github.com/HXChow/project

Setup.py 里面的59-50行，138-152行
还有 myVideoWidget.py 
上面是关于这个播放窗口的代码
![image](https://user-images.githubusercontent.com/51086267/61183765-bc2e9800-a677-11e9-8da2-daff706f6ad7.png)

**Comment by 892768447** [comment]
单独测试MainUI.py 在最底部添加代码,运行MainUI.py测试切换没有出现问题，
检查下Setup.py中或者其他功能代码中是否逻辑错误。或者重新添加了widget进去
```python
if __name__ == '__main__':
    import sys
    from PyQt5.QtWidgets import QApplication
    app = QApplication(sys.argv)
    widget = QtWidgets.QMainWindow()
    w = Ui_MainWindow()
    w.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())
```

**Comment by HXChow** [comment]
> 单独测试MainUI.py 在最底部添加代码,运行MainUI.py测试切换没有出现问题，
> 检查下Setup.py中或者其他功能代码中是否逻辑错误。或者重新添加了widget进去
> if __name__ == '__main__':
>     import sys
>     from PyQt5.QtWidgets import QApplication
>     app = QApplication(sys.argv)
>     widget = QtWidgets.QMainWindow()
>     w = Ui_MainWindow()
>     w.setupUi(widget)
>     widget.show()
>     sys.exit(app.exec_())

单独测试没问题
self.player.setVideoOutput(self.widget)  
把这一条注释掉就不会出现这些问题，但是这又是播放视频的关键代码
涉及到播放代码除了上述的地方外还有一个是将合成后的视频自动在widget上预览的槽函数
![image](https://user-images.githubusercontent.com/51086267/61184597-45e36300-a682-11e9-93cd-bc8ccd9c011c.png)
图里的Update3就是自动预览的槽函数，但是这也不影响

**Comment by 892768447** [comment]
你把代码单独放到MainUi.py里去测试。并没有发现有异常。甚至可以播放下视频试试
```python
self.player = QMediaPlayer()
self.player.setVideoOutput(self.widget)  # 视频播放输出的widget
```

**Comment by HXChow** [comment]
> 你把代码单独放到MainUi.py里去测试。并没有发现有异常。甚至可以播放下视频试试
> self.player = QMediaPlayer()
> self.player.setVideoOutput(self.widget)  # 视频播放输出的widget

单独放进去出现先前的情况
我在想是不是要用多线程来解决问题，有没有可行性？

**Comment by 892768447** [comment]
1. 这个就不清楚了，一般来说先测试能否正常显示界面：如单独运行MainUI.py
2. 在单独把QMediaPlayer加入进去测试播放视频有没有问题

你按照上面的先测试简单功能。主要是你的代码依赖太多我没法测试

**Comment by HXChow** [comment]
> 这个就不清楚了，一般来说先测试能否正常显示界面：如单独运行MainUI.py
> 在单独把QMediaPlayer加入进去测试播放视频有没有问题
> 
> 你按照上面的先测试简单功能。主要是你的代码依赖太多我没法测试

self.player = QMediaPlayer()
self.player.setVideoOutput(self.widget)  # 视频播放输出的widget
单独放进去测试加这两行就不能正常显示了
然后再加入播放功能测试，测试结果正常，视频能播放
