### ISSUE TITLE
[问题]Pyqt连接Oracle数据库需要装什么驱动么

### ISSUE THREAD

**Issue by tangyongda897** [PyQt5/PyQt#64]
db = QtSql.QSqlDatabase.addDatabase('QOCI')
        db.setHostName('192.168.101.81')
        db.setDatabaseName('orcl')
        db.setUserName('ankole')
        db.setPassword('jsdx_1234')
        db.setPort(1521)
        dbconn=db.open
        print(db.open())
这样子返回是false，不知道怎么搞

**Comment by 892768447** [comment]
Oracle数据库链接需要自带的那个dll数据库驱动文件。你试试复制到当前目录。或者搜索下Qt Oracle数据库链接的相关资料

**Comment by tangyongda897** [comment]
好的，十分感谢
