### ISSUE TITLE
设置QTextEdit的部分字符只读

### ISSUE THREAD

**Issue by dongzhang0725** [PyQt5/PyQt#65]
**Environment :** / 环境
 - OS: Win 10 [e.g. Win 10]
 - Python: 3.6.4 [e.g. 3.6.4 X64]
 - PyQt5: 5.10.1 [e.g. 5.10.1]

请问有没有办法只设置QTextEdit的部分字符只读？如图，我想设置inlutFile只读和可选，而其他字符串可以修改。

![image](https://user-images.githubusercontent.com/15956921/61191413-10b82e80-a6dd-11e9-88ca-1d000049f19c.png)

**Comment by 892768447** [comment]
好像没有直接的方法可以这样，不过可以结合多个信号或者函数来达到类似的效果，比如`selectionChanged` 信号 https://doc.qt.io/qt-5/qtextedit.html#selectionChanged ，setReadonly等等。需要自己实现这样的逻辑

**Comment by dongzhang0725** [comment]
好的，多谢。
