### ISSUE TITLE
调用QTcpServer中listen方法耗时太长，是不是在PyQt5中对QtNetwork支持不是很好呢？

### ISSUE THREAD

**Issue by meichuanneiku** [PyQt5/PyQt#66]
**Environment :** / 环境
 - OS: win7 [e.g. Win 10]
 - Python :3.7.1 X64 [e.g. 3.6.4 X64]
 - PyQt5: PyQt5.13.1  [e.g. 5.10.1]

在线程中开启Socket服务端，可是在开启监听时，耗时太长，在Qt下运行是没有问题的，这是为什么呢？

![image](https://user-images.githubusercontent.com/8164375/61277417-b86c5400-a7e4-11e9-846e-67043794f0aa.png)

**Comment by 625781186** [comment]
@meichuanneiku
你这主线程和子线程是同一个线程啊

**Comment by 892768447** [comment]
这样计时试试：

**Comment by meichuanneiku** [comment]
> @meichuanneiku
> 你这主线程和子线程是同一个线程啊，同一个线程就变成同步操作了。

呃，是图上错了，不好意思

**Comment by meichuanneiku** [comment]
> time.time() -t

![image](https://user-images.githubusercontent.com/8164375/61278189-485ecd80-a7e6-11e9-801c-a29811b9d6d8.png)
shi时间一样的，还是14s

**Comment by 892768447** [comment]
这个可能和你的电脑和网络环境有关系了
![QQ截图20190716183415](https://user-images.githubusercontent.com/5131669/61287884-7baa5800-a7f8-11e9-8d57-9f9c91476261.png)

```python
from PyQt5.QtNetwork import QTcpServer, QHostAddress
from PyQt5.QtCore import QCoreApplication
import time
app = QCoreApplication
def test():
    t = time.time()
    server = QTcpServer()
    server.listen(QHostAddress('127.0.0.1'), 9966)
    print('time:', time.time() - t)

test()
```

time: 0.4071006774902344
