### ISSUE TITLE
[问题]pyqt5中的Qt Designer 的自定义插件问题

### ISSUE THREAD

**Issue by ZZZxw** [PyQt5/PyQt#69]
![image](https://user-images.githubusercontent.com/37925763/61590408-56985980-abeb-11e9-8f24-c24a16ecc598.png)
如图，我想在Qt Desinger 导入自定义插件，但是我的desiger并没有这个Pyqt examples
谢谢！

**Comment by 625781186** [comment]
@ZZZxw 
按照文章里的步骤一步一步执行 , 
然后把每一步的步骤截图发上来.
包括文章中提到的目录的截图.

**Comment by ZZZxw** [comment]
![image](https://user-images.githubusercontent.com/37925763/61590644-0622fb00-abef-11e9-83eb-978f409ed537.png)
![image](https://user-images.githubusercontent.com/37925763/61590645-0cb17280-abef-11e9-9e57-7db7df8f9789.png)

**Comment by 625781186** [comment]
![image](https://user-images.githubusercontent.com/30521429/61590892-8b0f1400-abf1-11e9-8619-1abfdf604635.png)
测试没问题 , 不知道你的情况.

**Comment by 625781186** [comment]
或者看这个库
https://github.com/my-pyqt-learning/pydm

**Comment by ZZZxw** [comment]
![image](https://user-images.githubusercontent.com/37925763/61591214-813bdf80-abf6-11e9-89cd-89be722ae474.png)
我用第一种方法但是我的pyqt5的文件夹中都没有examples，是把下载的文件全部拖过来吗？它提示要更新__init__, 也更新？
