### ISSUE TITLE
[问题]线程的终止

### ISSUE THREAD

**Issue by HXChow** [PyQt5/PyQt#71]
**Environment :** / 环境
 - OS: win 10
 - Python 3.7.3 x64
 - PyQt5 [5.10.1

想通过一个按钮的按下与未按下来实现功能的开始与结束

![image](https://user-images.githubusercontent.com/51086267/61649666-7b242c80-ace4-11e9-8938-8d2038f7ea55.png)
![image](https://user-images.githubusercontent.com/51086267/61649725-9f800900-ace4-11e9-97af-9b1dc0210e38.png)
这是原来没用这个功能前的代码，分别是按钮连接的槽函数和实现功能的多线程代码
原来点下按钮后只能等待进程结束

现在想用下面的这种方法来达到按下就执行，再按一次后就停止执行
请问后面else那里改怎么写才能停止原来的线程
![image](https://user-images.githubusercontent.com/51086267/61650528-7fe9e000-ace6-11e9-8203-ed1378908278.png)

**Comment by 892768447** [comment]
常理是在线程里加上一个flag标志true或者false来中断循环之类的然线程自动退出。但是你这里没有。用不建议的函数`terminate`，文档：https://doc.qt.io/qt-5/qthread.html#terminate
