### ISSUE TITLE
[QcheckBox复选框切换窗口]

### ISSUE THREAD

**Issue by xiaokun-oo** [PyQt5/PyQt#73]
**Environment :** / 环境
 - OS: [e.g. Win 10]
 - Python [e.g. 3.6.4 X64]
 - PyQt5 [e.g. 5.10.1]
 - VScode
   我用 QT Dedigner 创建了一个主界面（MainWindow）和一个副界面（Dialog）。现在我想点击主界面的一个QcheckBox复选框来控制副界面（Dialog）的打开与关闭。那么我需要怎样初始化界面，定义信号槽来实现这个功能呢？

![image](https://user-images.githubusercontent.com/53340584/61951289-2da90780-afe3-11e9-9ae1-1eb9406ac2ae.png)

代码：

import sys
from PyQt5 import QtWidgets, QtCore
from PyQt5.QtWidgets import QFileDialog, QMessageBox, QDockWidget, QListWidget, QMainWindow, QDialog, QCheckBox, QWidget
from Ui_primaryUI import Ui_MainWindow  # 声明 主界面
from Ui_Receiving_display import Ui_Receiving_Display  # 声明 接收显示界面
from Ui_Rotation_Angle_display import Ui_Rotation_Angle_Display  # 声明 旋转角度显示界面
from Ui_Tilt_Angle_display import Ui_Tilt_Angle_Display  # 声明 倾角显示接面

class MyWindow(QtWidgets.QMainWindow, Ui_MainWindow):  # 继承QWidget和Ui_Form
    def __init__(self):
        super(MyWindow, self).__init__()  # 超级加载
        self.setupUi(self)  # 设置界面

class ReceiveWindow(QDialog, Ui_Receiving_Display):
    def __init__(self):
        super(ReceiveWindow, self).__init__()  # 超级加载
        self.setupUi(self)

class InclinationWindow(QDialog, Ui_Tilt_Angle_Display):
    def __init__(self):
        super(InclinationWindow, self).__init__()  # 超级加载
        self.setupUi(self)

class Rotating_angleWindow(QDialog, Ui_Rotation_Angle_Display):
    def __init__(self):
        super(Rotating_angleWindow, self).__init__()  # 超级加载
        self.setupUi(self)

if __name__ == '__main__':  # 如果整个程序是主函数
    # QApplication相当于main函数，也就是整个程序（很多文件）的主入口函数。
    # 对于GUI程序必须至少有一个这样的实例来让程序运行。
    app = QtWidgets.QApplication(sys.argv)
    # 生成 mywindow 类的实例
    myshow = MyWindow()  # 生成mywindow类的实例 myshow
    myshow.show()  # myshow调用show方法
    # 调用sys库的exit退出方法，条件是app.exec_()，也就是整个窗口关闭。
    # 有时候退出程序后，sys.exit(app.exec_())会报错，改用app.exec_()就没事
    # https://stackoverflow.com/questions/25719524/difference-between-sys-exitapp-exec-and-app-exec
    sys.exit(app.exec_())

**Comment by 625781186** [comment]
@xiaokun-oo 
第一 ：你的代码不可读 ， 请使用编辑器里的代码块功能 ；
第二 ： 群里有视频教程 。

**Comment by 892768447** [comment]
@xiaokun-oo 首先第一点，QDialog通过模态方式显示后是没法点击主界面的任何控件的。
第二点，通过信号槽来控制显示与关闭：如何使用信号槽结合控件的文档
结合这两篇文章 https://pyqt5.com/viewapi.html 和 https://pyqt5.com/bindsignals.html
