### ISSUE TITLE
[Question]QLineEdit does not stop iteration while waiting event editingFinished() or returnPressed()

### ISSUE THREAD

**Issue by Mathieu1972** [PyQt5/PyQt#75]
**Environment :** 
 - **OS:  Win 10**
 - **Python 3.5.7**
 - **PyQt5**

The "for" loop containing the **QlineEdit** is supposed to wait for a **Return** keypressed or **Enter** key pressed and then process the _self.Enterpressed_dosomething_ method if the following command receive the signal (here _editingFinished_).
 _self.lineEdit.editingFinished.connect(self.Enterpressed_dosomething)_

Instead of that, the loop finishes all the iteration and then the **QlineEdit** widget continues to activate _self.Enterpressed_dosomething_ method when Enter or Returned pressed whereas the loop is finished.
**How can i make the loop wait for the signals (returnPressed or editingFinished or textChanged )?**

**Comment by 892768447** [comment]
Sorry, I don't quite understand. Can you provide some test code? about loop and Signal

**Comment by Mathieu1972** [comment]
As example:
_for i in range(3):
 self.lineEdit.setCursorPosition(1)
 self.lineEdit.setInputMask('nnnnnnnnnnnnnnnnnnnnnn')
 self.lineEdit.editingFinished.connect(self.Enterpressed_dosomething)
 print('Current item in loop ='+str(i))

def Enterpressed_dosomething(self):
 texttocatch=self.lineEdit.text()_

But it will directly give :
Current item in loop =0
Current item in loop =1
Current item in loop =2
Without waiting the signal editingFinished to be sent....

**Comment by 625781186** [comment]
@Mathieu1972 
You can use `yield`,
this example :
<details>
<summary>example </summary>

# coding=utf-8

from PyQt5 import QtGui, QtWidgets, QtCore
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import sys


class MainWindow(QMainWindow):
    """
    Class documentation goes here.
    """

    def __init__(self, parent=None, *a, **kw):
        super().__init__(parent)
        self.lineEdit = QLineEdit(self)
        self.lineEdit.returnPressed.connect(self.do_something)
        self.generator = self.__creatr_generator()
        next(self.generator)
    def __creatr_generator(self):
        for i in range(3):
            self.lineEdit.setCursorPosition(1)

            self.lineEdit.setInputMask('nnnnnnnnnnnnnnnnnnnnnn')

            yield print('Current item in loop =' + str(i))

    def do_something(self):
        try:
            next(self.generator)
        except StopIteration:
            pass


if __name__ == "__main__":
    app = QApplication(sys.argv)
    app.setStyle(QStyleFactory.create("Fusion"))

    ui = MainWindow()
    ui.show()
    sys.exit(app.exec_())


</details>

**Comment by 892768447** [comment]
Normally, setting properties and binding signals should be placed in _init_ rather than in for loops, because Qt's event loops are blocked in fast for or while loops.

For example:
```python
for i in range(999999):
    print(i)

i = 0
while i < 9999:
    print(i)
    i += 1
```
the example code  block Qt  event loop.

You can use a short `sleep` in your code, and use `QApplication::processEvents()`

**Comment by 892768447** [comment]
```python
from PyQt5.QtCore import QThread
from PyQt5.QtWidgets import QWidget, QVBoxLayout, QLineEdit, QPushButton


class Window(QWidget):

    def __init__(self, *args, **kwargs):
        super(Window, self).__init__(*args, **kwargs)
        layout = QVBoxLayout(self)
        self.lineEdit = QLineEdit(self)
        self.lineEdit.returnPressed.connect(self.onReturnPressed)
        self.lineEdit.editingFinished.connect(self.onEditingFinished)
        self.lineEdit.textChanged.connect(self.onTextChanged)
        layout.addWidget(self.lineEdit)

        layout.addWidget(QPushButton(
            'Click to test while loop', self, clicked=self.doTestFor))

    def doTestFor(self):
        self.sender().setEnabled(False)
        while self.isVisible():
            # print('in while loop')
            QApplication.processEvents()
            QThread.msleep(0)

    def onReturnPressed(self):
        print('onReturnPressed: ', self.lineEdit.text())

    def onEditingFinished(self):
        print('onEditingFinished: ', self.lineEdit.text())

    def onTextChanged(self, text):
        print('onTextChanged: ', text)


if __name__ == '__main__':
    import sys
    from PyQt5.QtWidgets import QApplication
    app = QApplication(sys.argv)
    w = Window()
    w.show()
    sys.exit(app.exec_())
```

Output:
```
onEditingFinished:  
onTextChanged:  2
onTextChanged:  21
onTextChanged:  213
onTextChanged:  2134
onTextChanged:  21342
onTextChanged:  213424
onTextChanged:  2134243
onTextChanged:  21342432
onTextChanged:  213424324
onEditingFinished:  213424324
```

**Comment by Mathieu1972** [comment]
@892768447  your program works, but not in my case, the difference in my GUI is that it is generated by QTDesigner and it is loaded with:
_filenamegui='Guieditor.ui'_
_super(MyGUI, self).__init__()_
_self.win=uic.loadUi(filenamegui, self)_  
I have inserted the connection inside __init__ () part but i have still the same problem..

**Comment by 892768447** [comment]
@Mathieu1972  is same as

```python
from PyQt5.QtCore import QThread
from PyQt5.QtWidgets import QWidget, QVBoxLayout, QLineEdit, QPushButton


class Window(QWidget):

    def __init__(self, *args, **kwargs):
        super(Window, self).__init__(*args, **kwargs)
        # Load Ui File
        uic.loadUi('xxx.ui', self)
        # Bind Signals
        self.lineEdit.returnPressed.connect(self.onReturnPressed)
        self.lineEdit.editingFinished.connect(self.onEditingFinished)
        self.lineEdit.textChanged.connect(self.onTextChanged)

    def doTestFor(self):
        self.sender().setEnabled(False)
        while self.isVisible():
            # print('in while loop')
            QApplication.processEvents()
            QThread.msleep(0)

    def onReturnPressed(self):
        print('onReturnPressed: ', self.lineEdit.text())

    def onEditingFinished(self):
        print('onEditingFinished: ', self.lineEdit.text())

    def onTextChanged(self, text):
        print('onTextChanged: ', text)


if __name__ == '__main__':
    import sys
    from PyQt5.QtWidgets import QApplication
    app = QApplication(sys.argv)
    w = Window()
    w.show()
    sys.exit(app.exec_())
```

**Comment by Mathieu1972** [comment]
@892768447 I have tried and it does not stop the loop.

**Comment by 892768447** [comment]
@Mathieu1972  Okey, can you show me your UI file and test code?

**Comment by Mathieu1972** [comment]
@625781186 has found the solution. It takes advantage of the fundamental property of the generator that suspends a function until it receives the next(generator) command. I have inserted the yield in the loop "for" in a function and the next(generator) command inserted in the called function by the signal from QLineEdit. All is now well synchronized !
Thank you all for your precious support !
