### ISSUE TITLE
[问题] unicode strings are not supported, please encode to bytes

### ISSUE THREAD

**Issue by xiaokun-oo** [PyQt5/PyQt#76]
Environment :

 - OS: [e.g. Win 10]
 - Python [e.g. 3.6.4 X64]
 - PyQt5 [e.g. 5.10.1]

1、在主线程QtextBrowser中读到的字符串，经过转码处理后，发送到串口线程的变量中，再经过串口发送出去。但是在发送时程序报错 TypeError: unicode strings are not supported, please encode to bytes: '' 。如果我在判断串口是否打来前加上一句  print(self.txbuf)  就不会出现问题，功能会正常。请问这是什么原因？有什么解决办法？

---
线程内的全局变量
```
   def init(self):
        self.txbuf = ''  # 发送数据缓存
```

发送函数
```
   def senddata(self):  # 数据发送
        # print(self.txbuf)
        if self.ser.isOpen():  # 如果串口已经打开
            if self.txbuf != ' ':  # 如果 txbuf 中不是空的
                send_bytes_Num = self.ser.write(self.txbuf)       # 发送数据,并返回发送字节数
                self.txbytenum.emit(send_bytes_Num)  # 将数据发送到主线程，统计发送字节数
```

**Comment by 892768447** [comment]
@xiaokun-oo   self.ser.write(bytes类型)

 self.ser.write(self.txbuf.encode())

**Comment by xiaokun-oo** [comment]
@892768447
出现了新的错误：
        AttributeError: 'bytes' object has no attribute 'encode'
`send_bytes_Num = self.ser.write(self.txbuf.encode())       # 发送数据,并返回发送字节数`

**Comment by 892768447** [comment]
@xiaokun-oo 你判断下，意思就是你这个变量一会儿是str 一会儿是bytes。肯定不行啊 ，自己的逻辑自己写来控制下，判断是str类型才用encode
