### ISSUE TITLE
使用第三方的自定义控件，编译时报错‘’没有模块‘’

### ISSUE THREAD

**Issue by xiaokun-oo** [PyQt5/PyQt#78]
Environment :
 - OS: [e.g. Win 10]
 - Python [e.g. 3.6.4 X64]
 - PyQt5 [e.g. 5.10.1]
    我在 QT Designer 中已经添加了自定义的控件，保存成Ui文件后，在VSCODE 中编译成PY文件后，编译工程时会提示我没有模块？发生异常: ModuleNotFoundError No module named 'gaugecolor'
    我是还有什么东西没有添加吗？

![image](https://user-images.githubusercontent.com/53340584/62408984-62304b00-b603-11e9-9e11-12bce9e59b45.png)
![image](https://user-images.githubusercontent.com/53340584/62408995-7ecc8300-b603-11e9-81ed-c763c5dad690.png)

![image](https://user-images.githubusercontent.com/53340584/62409017-c94dff80-b603-11e9-9b3f-c257fe5690f8.png)

**Comment by 892768447** [comment]
这个库应该是c++的，好像还没有提供PyQt的绑定，无法使用，具体问一下作者

**Comment by 892768447** [comment]
@xiaokun-oo 看下除了quc.dll 应该会提供一个quc的pyd在外面给程序使用。就像 QWidgets.dll一样
