### ISSUE TITLE
[问题]QAxWidget嵌入Word、Excel后如何覆盖一层透明的画板

### ISSUE THREAD

**Issue by gcrv** [PyQt5/PyQt#80]
QAxWidget嵌入Word、Excel后如何覆盖一层透明的画板。画板本身已经设置透明，但覆盖之后就被填充了颜色，如何解决呢？

**Comment by 892768447** [comment]
![QQ截图20190805212917](https://user-images.githubusercontent.com/5131669/62468210-1aa6ec00-b7c8-11e9-82ce-f8ffc4bce878.png)
目前直接 盖上面有很多问题，鼠标穿透问题，背景透明也会被变成不透明
