### ISSUE TITLE
[问题]收缩窗口宽时，Flowlayout布局，窗口与单元之间存在1px的空间，求解。谢谢

### ISSUE THREAD

**Issue by chybcool** [PyQt5/PyQt#82]
**Environment :** / 环境
 - OS: [e.g. Win 7]
 - Python [e.g. 2.7.15]
 - PyQt4 [e.g. 4]

1.Flowlayout 流布局 窗口与最右单元之间存在1px的空间，理想效果应该窗口与单元之间不存在任何空间，单元布局内外设为0,单元与单元之间紧靠的。不知怎么修改才能达到右边单元与窗口之间不存在1px的空隙；

2.演示如图：（设单元宽200px，高100px，单元总宽为1000px，当收缩窗口时最小宽时却是1001px,多出1px的宽）
[演示：](http://chuantu.xyz/t6/702/1565610452x2890191699.gif)

代码：
[flowlayouttest.zip](https://github.com/PyQt5/PyQt/files/3492162/flowlayouttest.zip)

**Comment by 892768447** [comment]
具体看下doLayout函数里面怎么计算排列的。可以自由实现各种排列方式。
初步调试了下
可以把 `if nextX - spaceX > rect.right() and lineHeight > 0:` 修改为 `if nextX - spaceX > rect.right() + 1 and lineHeight > 0:`
