### ISSUE TITLE
[问题] 点击任意QWidget单元某控件时，其余所有单元里的控件都要非选中状态，求解。谢谢

### ISSUE THREAD

**Issue by chybcool** [PyQt5/PyQt#83]
**Environment :** / 环境
 - OS: [e.g. Win 7]
 - Python [e.g.2.7.15]
 - PyQt4 [e.g. 4]

1.目前实现任意一个单元格里的两个按钮可以有单选状态，现在问题是点击一个单元里控件时，再点击其它单元里的控件，两个单元里的控件都是选中状态，应该点击任意单元里某个控件，其它所有单元里的控件都是非选中状态，不是禁止选择。

2.[演示](http://chuantu.xyz/t6/702/1565771104x1033347913.gif)

[qingjiaodemo.zip](https://github.com/PyQt5/PyQt/files/3500447/qingjiaodemo.zip)

**Comment by 892768447** [comment]
https://doc.qt.io/qt-5/qbuttongroup.html

**Comment by chybcool** [comment]
在单元里对控件用了qbuttongroup，实现了单元内的控件单选，对qwidget所有单元也可以用来互拆？

**Comment by 892768447** [comment]
所有控件里的按钮 都加入到同一个qbuttongroup

**Comment by chybcool** [comment]
for i in range(self.rowslist):
            grid_widget = QtGui.QWidget()
            grid_widget.setFixedSize(self.cabinetw,self.cabineth)
            grid_widget.setContentsMargins(0,0,0,0)

            TopButton = QtGui.QPushButton()
            TopButton.setFlat(True)
            TopButton.setText(u"上")
            TopButton.setCheckable(True)
            TopButton.i = i
            self.TopButtons.append(TopButton)

            BottomButton = QtGui.QPushButton()
            BottomButton.setFlat(True)
            BottomButton.setCheckable(True)
            BottomButton.setText(u"下")
            BottomButton.i = i
            self.BottomButtons.append(BottomButton)

            QButtonGroup = QtGui.QButtonGroup()
            QButtonGroup.addButton(TopButton)
            QButtonGroup.addButton(BottomButton)
            QButtonGroup.i=i
            QButtonGroup.setExclusive(True)
            QButtonGroup.buttonClicked.connect(self.getScope)
            self.QButtonGroups.append(QButtonGroup)

            self.cell = QtGui.QGridLayout()
            self.cell.setSpacing(0)
            self.cell.addWidget(TopButton,1,1,1,3)
            self.cell.addWidget(BottomButton,2,1,1, 3)
            grid_widget.setLayout(self.cell)

            flowlayout.addWidget(grid_widget)
        self.setLayout(flowlayout)

**Comment by 892768447** [comment]
QButtonGroup = QtGui.QButtonGroup()  不要放在for循环里。。

放到最最最最最最最最最最最最最最最最最最最最最最最最最最最最最最最外面。只要一个
