### ISSUE TITLE
[问题] ((python)matplotlib  vs (Qt)QtChart)

### ISSUE THREAD

**Issue by xdwgood** [PyQt5/PyQt#86]
我之前使用pyqt画图使用这个模块matplotlib.
刚刚开到QtChart也可以实现类似的功能.
请问大家：使用pyqt制作上位机的时候，用哪个画图更好?  （也许是自己喜欢就好？ :smiley: ）
感谢大家.

**Comment by 892768447** [comment]
QtChart很多功能相比mat没有那么完善。且资料相对较少

**Comment by 892768447** [comment]
简单功能可以尝试用QtChart，需要花大量的时间去研究

**Comment by xdwgood** [comment]
@892768447  谢谢回复，让我来关闭这个问题 :smiley:
