### ISSUE TITLE
Error: no Qt platform plugin Could be installed

### ISSUE THREAD

**Issue by baby-lynch** [PyQt5/PyQt#94]
Error详情：This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

可能的修复方案：
1. 修改python环境安装路径，或者在新路径下重新下载安装python环境
2. 在新的python环境下重新安装pyqt5
3. 在Django中用新安装的python环境作为当前Qt项目解释器，

个人案例：
重新安装python环境：在D盘新建了一个python35文件夹，并在其中重新安装python35
重新安装PyQt5：在cmd执行D:\Python35\Python35\python.exe -m install PyQt5(注意路径不要弄错)

完成后不再报错

**Comment by 892768447** [comment]
1、检查安装路径中是否有中文
2、检查PyQt5/Qt/bin下是否有qt.conf(可能非必须)
3、检查环境变量中是否有其他包含Qt的路径影响(
如Anaconda集成环境等)
4、检查否为虚拟环境异常(如pycharm创建的)

**Comment by 892768447** [comment]
解压放到：Python35\Lib\site-packages\PyQt5\Qt\bin
[qt.zip](https://github.com/PyQt5/PyQt/files/3742668/qt.zip)
