### ISSUE TITLE
[按钮鼠标双击的时候触发单击] 

### ISSUE THREAD

**Issue by Yangcocoai** [PyQt5/PyQt#96]
**Environment :** / 环境
 - OS: [e.g. Win 10]
 - Python [e.g. 3.6.4 X64]
 - PyQt5 [e.g. 5.10.1]

# 解决 按钮双击的时候会触发单击的问题

from PyQt5.Qt import *

class MyLabel(QPushButton):
    def __init__(self,parent=None):
        super(MyLabel,self).__init__(parent)
        self.justDoubleClicked = False

    def mouseDoubleClickEvent(self,e):
        self.justDoubleClicked = True
        print("鼠标双击")

    def mousePressEvent(self,e):

        self.justDoubleClicked = False
        print('鼠标单击')

    def focusInEvent(self,e):
        print ('聚焦')
    def focusOutEvent(self,e):
        print ('focusOutEvent')
    def moveEvent(self,e):
        print ('移动事件')
    def leaveEvent(self,e): #鼠标离开label
        self.justDoubleClicked = False
        print("离开事件")
    def enterEvent(self,e): #鼠标移入label
        print ('进入事件')
    def mouseMoveEvent(self,e):
        print ('鼠标事件')

# 继承主窗口对象
class Windows(QWidget):
    def __init__(self):
        super().__init__()  # 执行 QWidget.__init__ 里面的文件
        self.setWindowTitle("窗口名")  # 窗口名
        self.resize(500,500)  # 窗口大小
        self.setup_ui()  # 控件

    # 控件
    def setup_ui(self):
        putton = MyLabel(self)
        putton.setParent(self)
        putton.move(50,50)

if __name__ == '__main__':
    import sys
    app = QApplication(sys.argv)
    windows = Windows()
    windows.show()
    sys.exit(app.exec_())

![image](https://user-images.githubusercontent.com/41054737/67155383-c7612600-f340-11e9-92c1-01c8c7b33a8c.png)

**Comment by 625781186** [comment]
这是qt的问题 自己用个 变量 + 定时器 来判断

**Comment by Yangcocoai** [comment]
> 这是qt的问题自己用个变量+计时器来判断

添加一个计时器，在短时间内没有第二次点击，就认为是一个单击事件。
就必须要添加一个计时器来解决是嘛？

**Comment by 625781186** [comment]
@Yangcocoai 
```
from PyQt5 import  QtGui, QtWidgets, QtCore
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import sys
class MyLabel(QLabel):
    isDouble = False
    def __init__(self,parent=None):
        super(MyLabel,self).__init__(parent)
    def mouseDoubleClickEvent(self,e):
        self.isDouble = True
    def mousePressEvent(self,e):
        QTimer.singleShot(300,lambda:self.__judge_click(e))
        
    def __judge_click(self,e):
        if self.isDouble == False:
            #单击
            print('mouse single clicked'   )
        else:
            #双击
            print('mouse double clicked'   )
 
class TestDialog(QDialog):
    def __init__(self,parent=None):
        super(TestDialog,self).__init__(parent)
        self.statusLabel = MyLabel(self)
        self.statusLabel.setGeometry(QtCore.QRect(95, 220, 151, 41))
        self.statusLabel.setText("hello label")
 
app=QApplication(sys.argv)
dialog=TestDialog()
dialog.show()
app.exec()
```

**Comment by Yangcocoai** [comment]
> @杨可可
> 
> ```python
> 从 PyQt5 导入   QtGui，QtWidgets，QtCore
>  从 PyQt5.QtCore 导入 * 
> 从 PyQt5.QtGui 导入 * 
> 从 PyQt5.QtWidgets 导入 * 
> 导入 sys
>  类 MyLabel（QLabel）：
>     isDouble =  False 
>     def  __init__（self，parent = None）：
>          超级（MyLabel，self）。__init__（父级）
>      def  mouseDoubleClickEvent（self，e）：
>          self .isDouble =  True 
>     def  mousePressEvent（self，e）：
>         QTimer.singleShot（300，lambda：self .__ judge_click（e））
>         
>     高清 __judge_click（自我，ē）：
>          如果 自 .isDouble ==  假：
>              ＃单击
> 
>             打印（'单击鼠标'    ）
>          else：
>              ＃双击
>             self .isDouble =  假
>             打印（'鼠标双击'    ）
>  
> 类 TestDialog（QDialog）：
>      def  __init__（self，parent = None）：
>          超级（TestDialog，self）。__init__（父）
>          自 .statusLabel = MyLabel（自）
>          自 .statusLabel.setGeometry（QtCore.QRect（95，220，151，41））
>          自 .statusLabel.setText（ “你好标签”）
>  
> 应用= QApplication（sys.argv）
> 对话框= TestDialog（）
> dialog.show（）
> app.exec（）
> ```

特别感谢。
但是我发现重写父类后。在单击使用原有的信号是不是就用不了了。我用的是按钮，
![image](https://user-images.githubusercontent.com/41054737/67157956-9f83b980-f364-11e9-9246-0ac772ec7f21.png)

![image](https://user-images.githubusercontent.com/41054737/67157968-d3f77580-f364-11e9-94ec-2af5e3038580.png)

这里的按钮信号和槽函数就没有执行。

**Comment by 625781186** [comment]
@Yangcocoai
这里改一下
![image](https://user-images.githubusercontent.com/30521429/67158059-09509300-f366-11e9-9d33-a6c76168c744.png)

**Comment by 625781186** [comment]
@Yangcocoai 
按钮不一样
https://stackoverflow.com/questions/25987166/pyqt5-qpushbutton-double-click
